// Code generated by Fern. DO NOT EDIT.

package dedicated_inference_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	godonext "github.com/harshmaru7/godo-next"
	client "github.com/harshmaru7/godo-next/client"
	option "github.com/harshmaru7/godo-next/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestDedicatedInferenceDedicatedInferencesGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferencesGetRequest{
		DedicatedInferenceID: "6b5c619c-359c-44ca-87e2-47e98170c01d",
	}
	_, invocationErr := client.DedicatedInference.DedicatedInferencesGet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesGetWithWireMock", "GET", "/v2/dedicated-inferences/6b5c619c-359c-44ca-87e2-47e98170c01d", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferencesDeleteRequest{
		DedicatedInferenceID: "6b5c619c-359c-44ca-87e2-47e98170c01d",
	}
	invocationErr := client.DedicatedInference.DedicatedInferencesDelete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesDeleteWithWireMock", "DELETE", "/v2/dedicated-inferences/6b5c619c-359c-44ca-87e2-47e98170c01d", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesPatchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferenceUpdateRequest{
		DedicatedInferenceID: "6b5c619c-359c-44ca-87e2-47e98170c01d",
	}
	_, invocationErr := client.DedicatedInference.DedicatedInferencesPatch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesPatchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesPatchWithWireMock", "PATCH", "/v2/dedicated-inferences/6b5c619c-359c-44ca-87e2-47e98170c01d", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferencesListRequest{}
	_, invocationErr := client.DedicatedInference.DedicatedInferencesList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesListWithWireMock", "GET", "/v2/dedicated-inferences", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferenceCreateRequest{
		Spec: &godonext.DedicatedInferenceSpec{
			Version: 1,
			Name:    "new-dedicated-inference",
			Region:  godonext.DedicatedInferenceSpecRegionAtl1,
			Vpc: &godonext.DedicatedInferenceSpecVpc{
				UUID: "997615ce-132d-4bae-9270-9ee21b395e5d",
			},
			EnablePublicEndpoint: true,
			ModelDeployments: []*godonext.ModelDeploymentSpec{
				&godonext.ModelDeploymentSpec{},
			},
		},
	}
	_, invocationErr := client.DedicatedInference.DedicatedInferencesCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesCreateWithWireMock", "POST", "/v2/dedicated-inferences", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesListAcceleratorsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferencesListAcceleratorsRequest{
		DedicatedInferenceID: "6b5c619c-359c-44ca-87e2-47e98170c01d",
		Slug: godonext.String(
			"gpu-mi300x1-192gb",
		),
	}
	_, invocationErr := client.DedicatedInference.DedicatedInferencesListAccelerators(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesListAcceleratorsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesListAcceleratorsWithWireMock", "GET", "/v2/dedicated-inferences/6b5c619c-359c-44ca-87e2-47e98170c01d/accelerators", map[string]interface{}{"slug": "gpu-mi300x1-192gb"}, 1)
}

func TestDedicatedInferenceDedicatedInferencesGetAcceleratorWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferencesGetAcceleratorRequest{
		DedicatedInferenceID: "6b5c619c-359c-44ca-87e2-47e98170c01d",
		AcceleratorID:        "5b5c619c-359c-44ca-87e2-47e98170c02f",
	}
	_, invocationErr := client.DedicatedInference.DedicatedInferencesGetAccelerator(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesGetAcceleratorWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesGetAcceleratorWithWireMock", "GET", "/v2/dedicated-inferences/6b5c619c-359c-44ca-87e2-47e98170c01d/accelerators/5b5c619c-359c-44ca-87e2-47e98170c02f", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesGetCaWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferencesGetCaRequest{
		DedicatedInferenceID: "6b5c619c-359c-44ca-87e2-47e98170c01d",
	}
	_, invocationErr := client.DedicatedInference.DedicatedInferencesGetCa(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesGetCaWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesGetCaWithWireMock", "GET", "/v2/dedicated-inferences/6b5c619c-359c-44ca-87e2-47e98170c01d/ca", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesListTokensWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferencesListTokensRequest{
		DedicatedInferenceID: "6b5c619c-359c-44ca-87e2-47e98170c01d",
	}
	_, invocationErr := client.DedicatedInference.DedicatedInferencesListTokens(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesListTokensWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesListTokensWithWireMock", "GET", "/v2/dedicated-inferences/6b5c619c-359c-44ca-87e2-47e98170c01d/tokens", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesCreateTokensWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferenceTokenCreateRequest{
		DedicatedInferenceID: "6b5c619c-359c-44ca-87e2-47e98170c01d",
		Name:                 "new-inference-token",
	}
	_, invocationErr := client.DedicatedInference.DedicatedInferencesCreateTokens(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesCreateTokensWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesCreateTokensWithWireMock", "POST", "/v2/dedicated-inferences/6b5c619c-359c-44ca-87e2-47e98170c01d/tokens", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesDeleteTokensWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.DedicatedInferencesDeleteTokensRequest{
		DedicatedInferenceID: "6b5c619c-359c-44ca-87e2-47e98170c01d",
		TokenID:              "f11d4795-c1db-4ac3-9aa6-a0ea3c58877e",
	}
	invocationErr := client.DedicatedInference.DedicatedInferencesDeleteTokens(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesDeleteTokensWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesDeleteTokensWithWireMock", "DELETE", "/v2/dedicated-inferences/6b5c619c-359c-44ca-87e2-47e98170c01d/tokens/f11d4795-c1db-4ac3-9aa6-a0ea3c58877e", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesListSizesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.DedicatedInference.DedicatedInferencesListSizes(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesListSizesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesListSizesWithWireMock", "GET", "/v2/dedicated-inferences/sizes", nil, 1)
}

func TestDedicatedInferenceDedicatedInferencesGetGpuModelConfigWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.DedicatedInference.DedicatedInferencesGetGpuModelConfig(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDedicatedInferenceDedicatedInferencesGetGpuModelConfigWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDedicatedInferenceDedicatedInferencesGetGpuModelConfigWithWireMock", "GET", "/v2/dedicated-inferences/gpu-model-config", nil, 1)
}
