// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/harshmaru7/godo-next/internal"
	big "math/big"
)

var (
	oneClicksCreateFieldAddonSlugs  = big.NewInt(1 << 0)
	oneClicksCreateFieldClusterUUID = big.NewInt(1 << 1)
)

type OneClicksCreate struct {
	// An array of 1-Click Application slugs to be installed to the Kubernetes cluster.
	AddonSlugs []string `json:"addon_slugs" url:"-"`
	// A unique ID for the Kubernetes cluster to which the 1-Click Applications will be installed.
	ClusterUUID string `json:"cluster_uuid" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (o *OneClicksCreate) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetAddonSlugs sets the AddonSlugs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OneClicksCreate) SetAddonSlugs(addonSlugs []string) {
	o.AddonSlugs = addonSlugs
	o.require(oneClicksCreateFieldAddonSlugs)
}

// SetClusterUUID sets the ClusterUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OneClicksCreate) SetClusterUUID(clusterUUID string) {
	o.ClusterUUID = clusterUUID
	o.require(oneClicksCreateFieldClusterUUID)
}

func (o *OneClicksCreate) UnmarshalJSON(data []byte) error {
	type unmarshaler OneClicksCreate
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*o = OneClicksCreate(body)
	return nil
}

func (o *OneClicksCreate) MarshalJSON() ([]byte, error) {
	type embed OneClicksCreate
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	oneClicksListRequestFieldType = big.NewInt(1 << 0)
)

type OneClicksListRequest struct {
	// Restrict results to a certain type of 1-Click.
	Type *OneClicksListRequestType `json:"-" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (o *OneClicksListRequest) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OneClicksListRequest) SetType(type_ *OneClicksListRequestType) {
	o.Type = type_
	o.require(oneClicksListRequestFieldType)
}

var (
	oneClicksInstallKubernetesResponseFieldMessage = big.NewInt(1 << 0)
)

type OneClicksInstallKubernetesResponse struct {
	// A message about the result of the request.
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OneClicksInstallKubernetesResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *OneClicksInstallKubernetesResponse) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OneClicksInstallKubernetesResponse) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OneClicksInstallKubernetesResponse) SetMessage(message *string) {
	o.Message = message
	o.require(oneClicksInstallKubernetesResponseFieldMessage)
}

func (o *OneClicksInstallKubernetesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OneClicksInstallKubernetesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OneClicksInstallKubernetesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OneClicksInstallKubernetesResponse) MarshalJSON() ([]byte, error) {
	type embed OneClicksInstallKubernetesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OneClicksInstallKubernetesResponse) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OneClicksListRequestType string

const (
	OneClicksListRequestTypeDroplet    OneClicksListRequestType = "droplet"
	OneClicksListRequestTypeKubernetes OneClicksListRequestType = "kubernetes"
)

func NewOneClicksListRequestTypeFromString(s string) (OneClicksListRequestType, error) {
	switch s {
	case "droplet":
		return OneClicksListRequestTypeDroplet, nil
	case "kubernetes":
		return OneClicksListRequestTypeKubernetes, nil
	}
	var t OneClicksListRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OneClicksListRequestType) Ptr() *OneClicksListRequestType {
	return &o
}

var (
	oneClicksListResponseFieldField1Clicks = big.NewInt(1 << 0)
)

type OneClicksListResponse struct {
	Field1Clicks []*OneClicks `json:"1_clicks,omitempty" url:"1_clicks,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OneClicksListResponse) GetField1Clicks() []*OneClicks {
	if o == nil {
		return nil
	}
	return o.Field1Clicks
}

func (o *OneClicksListResponse) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OneClicksListResponse) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetField1Clicks sets the Field1Clicks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OneClicksListResponse) SetField1Clicks(_1Clicks []*OneClicks) {
	o.Field1Clicks = _1Clicks
	o.require(oneClicksListResponseFieldField1Clicks)
}

func (o *OneClicksListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OneClicksListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OneClicksListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OneClicksListResponse) MarshalJSON() ([]byte, error) {
	type embed OneClicksListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OneClicksListResponse) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

var (
	oneClicksFieldSlug = big.NewInt(1 << 0)
	oneClicksFieldType = big.NewInt(1 << 1)
)

type OneClicks struct {
	// The slug identifier for the 1-Click application.
	Slug string `json:"slug" url:"slug"`
	// The type of the 1-Click application.
	Type string `json:"type" url:"type"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OneClicks) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *OneClicks) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *OneClicks) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OneClicks) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OneClicks) SetSlug(slug string) {
	o.Slug = slug
	o.require(oneClicksFieldSlug)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OneClicks) SetType(type_ string) {
	o.Type = type_
	o.require(oneClicksFieldType)
}

func (o *OneClicks) UnmarshalJSON(data []byte) error {
	type unmarshaler OneClicks
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OneClicks(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OneClicks) MarshalJSON() ([]byte, error) {
	type embed OneClicks
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OneClicks) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}
