// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/harshmaru7/godo-next/internal"
	big "math/big"
	time "time"
)

var (
	byoipPrefixCreateFieldPrefix    = big.NewInt(1 << 0)
	byoipPrefixCreateFieldRegion    = big.NewInt(1 << 1)
	byoipPrefixCreateFieldSignature = big.NewInt(1 << 2)
)

type ByoipPrefixCreate struct {
	// The IP prefix in CIDR notation to bring
	Prefix string `json:"prefix" url:"-"`
	// The region where the prefix will be created
	Region string `json:"region" url:"-"`
	// The signature hash for the prefix creation request
	Signature string `json:"signature" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *ByoipPrefixCreate) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixCreate) SetPrefix(prefix string) {
	b.Prefix = prefix
	b.require(byoipPrefixCreateFieldPrefix)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixCreate) SetRegion(region string) {
	b.Region = region
	b.require(byoipPrefixCreateFieldRegion)
}

// SetSignature sets the Signature field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixCreate) SetSignature(signature string) {
	b.Signature = signature
	b.require(byoipPrefixCreateFieldSignature)
}

func (b *ByoipPrefixCreate) UnmarshalJSON(data []byte) error {
	type unmarshaler ByoipPrefixCreate
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*b = ByoipPrefixCreate(body)
	return nil
}

func (b *ByoipPrefixCreate) MarshalJSON() ([]byte, error) {
	type embed ByoipPrefixCreate
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	byoipPrefixesDeleteRequestFieldByoipPrefixUUID = big.NewInt(1 << 0)
)

type ByoipPrefixesDeleteRequest struct {
	// The unique identifier for the BYOIP Prefix.
	ByoipPrefixUUID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *ByoipPrefixesDeleteRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetByoipPrefixUUID sets the ByoipPrefixUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesDeleteRequest) SetByoipPrefixUUID(byoipPrefixUUID string) {
	b.ByoipPrefixUUID = byoipPrefixUUID
	b.require(byoipPrefixesDeleteRequestFieldByoipPrefixUUID)
}

var (
	byoipPrefixesGetRequestFieldByoipPrefixUUID = big.NewInt(1 << 0)
)

type ByoipPrefixesGetRequest struct {
	// The unique identifier for the BYOIP Prefix.
	ByoipPrefixUUID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *ByoipPrefixesGetRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetByoipPrefixUUID sets the ByoipPrefixUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesGetRequest) SetByoipPrefixUUID(byoipPrefixUUID string) {
	b.ByoipPrefixUUID = byoipPrefixUUID
	b.require(byoipPrefixesGetRequestFieldByoipPrefixUUID)
}

var (
	byoipPrefixesListRequestFieldPerPage = big.NewInt(1 << 0)
	byoipPrefixesListRequestFieldPage    = big.NewInt(1 << 1)
)

type ByoipPrefixesListRequest struct {
	// Number of items returned per page
	PerPage *int `json:"-" url:"per_page,omitempty"`
	// Which 'page' of paginated results to return.
	Page *int `json:"-" url:"page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *ByoipPrefixesListRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListRequest) SetPerPage(perPage *int) {
	b.PerPage = perPage
	b.require(byoipPrefixesListRequestFieldPerPage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListRequest) SetPage(page *int) {
	b.Page = page
	b.require(byoipPrefixesListRequestFieldPage)
}

var (
	byoipPrefixesListResourcesRequestFieldByoipPrefixUUID = big.NewInt(1 << 0)
	byoipPrefixesListResourcesRequestFieldPerPage         = big.NewInt(1 << 1)
	byoipPrefixesListResourcesRequestFieldPage            = big.NewInt(1 << 2)
)

type ByoipPrefixesListResourcesRequest struct {
	// The unique identifier for the BYOIP Prefix.
	ByoipPrefixUUID string `json:"-" url:"-"`
	// Number of items returned per page
	PerPage *int `json:"-" url:"per_page,omitempty"`
	// Which 'page' of paginated results to return.
	Page *int `json:"-" url:"page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *ByoipPrefixesListResourcesRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetByoipPrefixUUID sets the ByoipPrefixUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListResourcesRequest) SetByoipPrefixUUID(byoipPrefixUUID string) {
	b.ByoipPrefixUUID = byoipPrefixUUID
	b.require(byoipPrefixesListResourcesRequestFieldByoipPrefixUUID)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListResourcesRequest) SetPerPage(perPage *int) {
	b.PerPage = perPage
	b.require(byoipPrefixesListResourcesRequestFieldPerPage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListResourcesRequest) SetPage(page *int) {
	b.Page = page
	b.require(byoipPrefixesListResourcesRequestFieldPage)
}

var (
	byoipPrefixUpdateFieldByoipPrefixUUID = big.NewInt(1 << 0)
	byoipPrefixUpdateFieldAdvertise       = big.NewInt(1 << 1)
)

type ByoipPrefixUpdate struct {
	// A unique identifier for a BYOIP prefix.
	ByoipPrefixUUID string `json:"-" url:"-"`
	// Whether the BYOIP prefix should be advertised
	Advertise *bool `json:"advertise,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *ByoipPrefixUpdate) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetByoipPrefixUUID sets the ByoipPrefixUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixUpdate) SetByoipPrefixUUID(byoipPrefixUUID string) {
	b.ByoipPrefixUUID = byoipPrefixUUID
	b.require(byoipPrefixUpdateFieldByoipPrefixUUID)
}

// SetAdvertise sets the Advertise field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixUpdate) SetAdvertise(advertise *bool) {
	b.Advertise = advertise
	b.require(byoipPrefixUpdateFieldAdvertise)
}

func (b *ByoipPrefixUpdate) UnmarshalJSON(data []byte) error {
	type unmarshaler ByoipPrefixUpdate
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*b = ByoipPrefixUpdate(body)
	return nil
}

func (b *ByoipPrefixUpdate) MarshalJSON() ([]byte, error) {
	type embed ByoipPrefixUpdate
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	byoipPrefixFieldUUID          = big.NewInt(1 << 0)
	byoipPrefixFieldName          = big.NewInt(1 << 1)
	byoipPrefixFieldPrefix        = big.NewInt(1 << 2)
	byoipPrefixFieldStatus        = big.NewInt(1 << 3)
	byoipPrefixFieldRegion        = big.NewInt(1 << 4)
	byoipPrefixFieldValidations   = big.NewInt(1 << 5)
	byoipPrefixFieldFailureReason = big.NewInt(1 << 6)
	byoipPrefixFieldLocked        = big.NewInt(1 << 7)
	byoipPrefixFieldAdvertised    = big.NewInt(1 << 8)
	byoipPrefixFieldProjectID     = big.NewInt(1 << 9)
)

type ByoipPrefix struct {
	// Unique identifier for the BYOIP prefix
	UUID *string `json:"uuid,omitempty" url:"uuid,omitempty"`
	// Name of the BYOIP prefix
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The IP prefix in CIDR notation
	Prefix *string `json:"prefix,omitempty" url:"prefix,omitempty"`
	// Status of the BYOIP prefix
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Region where the BYOIP prefix is located
	Region *string `json:"region,omitempty" url:"region,omitempty"`
	// List of validation statuses for the BYOIP prefix
	Validations []*ByoipPrefixValidationsItem `json:"validations,omitempty" url:"validations,omitempty"`
	// Reason for failure, if applicable
	FailureReason *string `json:"failure_reason,omitempty" url:"failure_reason,omitempty"`
	// Whether the BYOIP prefix is locked
	Locked *bool `json:"locked,omitempty" url:"locked,omitempty"`
	// Whether the BYOIP prefix is being advertised
	Advertised *bool `json:"advertised,omitempty" url:"advertised,omitempty"`
	// The ID of the project associated with the BYOIP prefix
	ProjectID *string `json:"project_id,omitempty" url:"project_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *ByoipPrefix) GetUUID() *string {
	if b == nil {
		return nil
	}
	return b.UUID
}

func (b *ByoipPrefix) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

func (b *ByoipPrefix) GetPrefix() *string {
	if b == nil {
		return nil
	}
	return b.Prefix
}

func (b *ByoipPrefix) GetStatus() *string {
	if b == nil {
		return nil
	}
	return b.Status
}

func (b *ByoipPrefix) GetRegion() *string {
	if b == nil {
		return nil
	}
	return b.Region
}

func (b *ByoipPrefix) GetValidations() []*ByoipPrefixValidationsItem {
	if b == nil {
		return nil
	}
	return b.Validations
}

func (b *ByoipPrefix) GetFailureReason() *string {
	if b == nil {
		return nil
	}
	return b.FailureReason
}

func (b *ByoipPrefix) GetLocked() *bool {
	if b == nil {
		return nil
	}
	return b.Locked
}

func (b *ByoipPrefix) GetAdvertised() *bool {
	if b == nil {
		return nil
	}
	return b.Advertised
}

func (b *ByoipPrefix) GetProjectID() *string {
	if b == nil {
		return nil
	}
	return b.ProjectID
}

func (b *ByoipPrefix) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *ByoipPrefix) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefix) SetUUID(uuid *string) {
	b.UUID = uuid
	b.require(byoipPrefixFieldUUID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefix) SetName(name *string) {
	b.Name = name
	b.require(byoipPrefixFieldName)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefix) SetPrefix(prefix *string) {
	b.Prefix = prefix
	b.require(byoipPrefixFieldPrefix)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefix) SetStatus(status *string) {
	b.Status = status
	b.require(byoipPrefixFieldStatus)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefix) SetRegion(region *string) {
	b.Region = region
	b.require(byoipPrefixFieldRegion)
}

// SetValidations sets the Validations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefix) SetValidations(validations []*ByoipPrefixValidationsItem) {
	b.Validations = validations
	b.require(byoipPrefixFieldValidations)
}

// SetFailureReason sets the FailureReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefix) SetFailureReason(failureReason *string) {
	b.FailureReason = failureReason
	b.require(byoipPrefixFieldFailureReason)
}

// SetLocked sets the Locked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefix) SetLocked(locked *bool) {
	b.Locked = locked
	b.require(byoipPrefixFieldLocked)
}

// SetAdvertised sets the Advertised field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefix) SetAdvertised(advertised *bool) {
	b.Advertised = advertised
	b.require(byoipPrefixFieldAdvertised)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefix) SetProjectID(projectID *string) {
	b.ProjectID = projectID
	b.require(byoipPrefixFieldProjectID)
}

func (b *ByoipPrefix) UnmarshalJSON(data []byte) error {
	type unmarshaler ByoipPrefix
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = ByoipPrefix(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *ByoipPrefix) MarshalJSON() ([]byte, error) {
	type embed ByoipPrefix
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *ByoipPrefix) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	byoipPrefixResourceFieldID         = big.NewInt(1 << 0)
	byoipPrefixResourceFieldByoip      = big.NewInt(1 << 1)
	byoipPrefixResourceFieldRegion     = big.NewInt(1 << 2)
	byoipPrefixResourceFieldResource   = big.NewInt(1 << 3)
	byoipPrefixResourceFieldAssignedAt = big.NewInt(1 << 4)
)

type ByoipPrefixResource struct {
	// Unique identifier for the allocation
	ID *int64 `json:"id,omitempty" url:"id,omitempty"`
	// The BYOIP prefix UUID
	Byoip *string `json:"byoip,omitempty" url:"byoip,omitempty"`
	// Region where the allocation is made
	Region *string `json:"region,omitempty" url:"region,omitempty"`
	// The resource associated with the allocation
	Resource *string `json:"resource,omitempty" url:"resource,omitempty"`
	// Time when the allocation was assigned
	AssignedAt *time.Time `json:"assigned_at,omitempty" url:"assigned_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *ByoipPrefixResource) GetID() *int64 {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *ByoipPrefixResource) GetByoip() *string {
	if b == nil {
		return nil
	}
	return b.Byoip
}

func (b *ByoipPrefixResource) GetRegion() *string {
	if b == nil {
		return nil
	}
	return b.Region
}

func (b *ByoipPrefixResource) GetResource() *string {
	if b == nil {
		return nil
	}
	return b.Resource
}

func (b *ByoipPrefixResource) GetAssignedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.AssignedAt
}

func (b *ByoipPrefixResource) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *ByoipPrefixResource) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixResource) SetID(id *int64) {
	b.ID = id
	b.require(byoipPrefixResourceFieldID)
}

// SetByoip sets the Byoip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixResource) SetByoip(byoip *string) {
	b.Byoip = byoip
	b.require(byoipPrefixResourceFieldByoip)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixResource) SetRegion(region *string) {
	b.Region = region
	b.require(byoipPrefixResourceFieldRegion)
}

// SetResource sets the Resource field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixResource) SetResource(resource *string) {
	b.Resource = resource
	b.require(byoipPrefixResourceFieldResource)
}

// SetAssignedAt sets the AssignedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixResource) SetAssignedAt(assignedAt *time.Time) {
	b.AssignedAt = assignedAt
	b.require(byoipPrefixResourceFieldAssignedAt)
}

func (b *ByoipPrefixResource) UnmarshalJSON(data []byte) error {
	type embed ByoipPrefixResource
	var unmarshaler = struct {
		embed
		AssignedAt *internal.DateTime `json:"assigned_at,omitempty"`
	}{
		embed: embed(*b),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*b = ByoipPrefixResource(unmarshaler.embed)
	b.AssignedAt = unmarshaler.AssignedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *ByoipPrefixResource) MarshalJSON() ([]byte, error) {
	type embed ByoipPrefixResource
	var marshaler = struct {
		embed
		AssignedAt *internal.DateTime `json:"assigned_at,omitempty"`
	}{
		embed:      embed(*b),
		AssignedAt: internal.NewOptionalDateTime(b.AssignedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *ByoipPrefixResource) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	byoipPrefixValidationsItemFieldName   = big.NewInt(1 << 0)
	byoipPrefixValidationsItemFieldStatus = big.NewInt(1 << 1)
	byoipPrefixValidationsItemFieldNote   = big.NewInt(1 << 2)
)

type ByoipPrefixValidationsItem struct {
	// Name of the validation
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Status of the validation
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Additional notes or details about the validation
	Note *string `json:"note,omitempty" url:"note,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *ByoipPrefixValidationsItem) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

func (b *ByoipPrefixValidationsItem) GetStatus() *string {
	if b == nil {
		return nil
	}
	return b.Status
}

func (b *ByoipPrefixValidationsItem) GetNote() *string {
	if b == nil {
		return nil
	}
	return b.Note
}

func (b *ByoipPrefixValidationsItem) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *ByoipPrefixValidationsItem) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixValidationsItem) SetName(name *string) {
	b.Name = name
	b.require(byoipPrefixValidationsItemFieldName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixValidationsItem) SetStatus(status *string) {
	b.Status = status
	b.require(byoipPrefixValidationsItemFieldStatus)
}

// SetNote sets the Note field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixValidationsItem) SetNote(note *string) {
	b.Note = note
	b.require(byoipPrefixValidationsItemFieldNote)
}

func (b *ByoipPrefixValidationsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ByoipPrefixValidationsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = ByoipPrefixValidationsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *ByoipPrefixValidationsItem) MarshalJSON() ([]byte, error) {
	type embed ByoipPrefixValidationsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *ByoipPrefixValidationsItem) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	byoipPrefixesCreateResponseFieldUUID   = big.NewInt(1 << 0)
	byoipPrefixesCreateResponseFieldRegion = big.NewInt(1 << 1)
	byoipPrefixesCreateResponseFieldStatus = big.NewInt(1 << 2)
)

type ByoipPrefixesCreateResponse struct {
	// The unique identifier for the BYOIP prefix
	UUID *string `json:"uuid,omitempty" url:"uuid,omitempty"`
	// The region where the prefix is created
	Region *string `json:"region,omitempty" url:"region,omitempty"`
	// The status of the BYOIP prefix
	Status *string `json:"status,omitempty" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *ByoipPrefixesCreateResponse) GetUUID() *string {
	if b == nil {
		return nil
	}
	return b.UUID
}

func (b *ByoipPrefixesCreateResponse) GetRegion() *string {
	if b == nil {
		return nil
	}
	return b.Region
}

func (b *ByoipPrefixesCreateResponse) GetStatus() *string {
	if b == nil {
		return nil
	}
	return b.Status
}

func (b *ByoipPrefixesCreateResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *ByoipPrefixesCreateResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesCreateResponse) SetUUID(uuid *string) {
	b.UUID = uuid
	b.require(byoipPrefixesCreateResponseFieldUUID)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesCreateResponse) SetRegion(region *string) {
	b.Region = region
	b.require(byoipPrefixesCreateResponseFieldRegion)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesCreateResponse) SetStatus(status *string) {
	b.Status = status
	b.require(byoipPrefixesCreateResponseFieldStatus)
}

func (b *ByoipPrefixesCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ByoipPrefixesCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = ByoipPrefixesCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *ByoipPrefixesCreateResponse) MarshalJSON() ([]byte, error) {
	type embed ByoipPrefixesCreateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *ByoipPrefixesCreateResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	byoipPrefixesGetResponseFieldByoipPrefix = big.NewInt(1 << 0)
)

type ByoipPrefixesGetResponse struct {
	ByoipPrefix *ByoipPrefix `json:"byoip_prefix,omitempty" url:"byoip_prefix,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *ByoipPrefixesGetResponse) GetByoipPrefix() *ByoipPrefix {
	if b == nil {
		return nil
	}
	return b.ByoipPrefix
}

func (b *ByoipPrefixesGetResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *ByoipPrefixesGetResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetByoipPrefix sets the ByoipPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesGetResponse) SetByoipPrefix(byoipPrefix *ByoipPrefix) {
	b.ByoipPrefix = byoipPrefix
	b.require(byoipPrefixesGetResponseFieldByoipPrefix)
}

func (b *ByoipPrefixesGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ByoipPrefixesGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = ByoipPrefixesGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *ByoipPrefixesGetResponse) MarshalJSON() ([]byte, error) {
	type embed ByoipPrefixesGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *ByoipPrefixesGetResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	byoipPrefixesListResourcesResponseFieldLinks = big.NewInt(1 << 0)
	byoipPrefixesListResourcesResponseFieldMeta  = big.NewInt(1 << 1)
	byoipPrefixesListResourcesResponseFieldIps   = big.NewInt(1 << 2)
)

type ByoipPrefixesListResourcesResponse struct {
	Links *PageLinks `json:"links,omitempty" url:"links,omitempty"`
	// Information about the response itself.
	Meta *MetaMeta              `json:"meta" url:"meta"`
	Ips  []*ByoipPrefixResource `json:"ips,omitempty" url:"ips,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *ByoipPrefixesListResourcesResponse) GetLinks() *PageLinks {
	if b == nil {
		return nil
	}
	return b.Links
}

func (b *ByoipPrefixesListResourcesResponse) GetMeta() *MetaMeta {
	if b == nil {
		return nil
	}
	return b.Meta
}

func (b *ByoipPrefixesListResourcesResponse) GetIps() []*ByoipPrefixResource {
	if b == nil {
		return nil
	}
	return b.Ips
}

func (b *ByoipPrefixesListResourcesResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *ByoipPrefixesListResourcesResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListResourcesResponse) SetLinks(links *PageLinks) {
	b.Links = links
	b.require(byoipPrefixesListResourcesResponseFieldLinks)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListResourcesResponse) SetMeta(meta *MetaMeta) {
	b.Meta = meta
	b.require(byoipPrefixesListResourcesResponseFieldMeta)
}

// SetIps sets the Ips field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListResourcesResponse) SetIps(ips []*ByoipPrefixResource) {
	b.Ips = ips
	b.require(byoipPrefixesListResourcesResponseFieldIps)
}

func (b *ByoipPrefixesListResourcesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ByoipPrefixesListResourcesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = ByoipPrefixesListResourcesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *ByoipPrefixesListResourcesResponse) MarshalJSON() ([]byte, error) {
	type embed ByoipPrefixesListResourcesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *ByoipPrefixesListResourcesResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	byoipPrefixesListResponseFieldLinks         = big.NewInt(1 << 0)
	byoipPrefixesListResponseFieldMeta          = big.NewInt(1 << 1)
	byoipPrefixesListResponseFieldByoipPrefixes = big.NewInt(1 << 2)
)

type ByoipPrefixesListResponse struct {
	Links *PageLinks `json:"links,omitempty" url:"links,omitempty"`
	// Information about the response itself.
	Meta          *MetaMeta      `json:"meta" url:"meta"`
	ByoipPrefixes []*ByoipPrefix `json:"byoip_prefixes,omitempty" url:"byoip_prefixes,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *ByoipPrefixesListResponse) GetLinks() *PageLinks {
	if b == nil {
		return nil
	}
	return b.Links
}

func (b *ByoipPrefixesListResponse) GetMeta() *MetaMeta {
	if b == nil {
		return nil
	}
	return b.Meta
}

func (b *ByoipPrefixesListResponse) GetByoipPrefixes() []*ByoipPrefix {
	if b == nil {
		return nil
	}
	return b.ByoipPrefixes
}

func (b *ByoipPrefixesListResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *ByoipPrefixesListResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListResponse) SetLinks(links *PageLinks) {
	b.Links = links
	b.require(byoipPrefixesListResponseFieldLinks)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListResponse) SetMeta(meta *MetaMeta) {
	b.Meta = meta
	b.require(byoipPrefixesListResponseFieldMeta)
}

// SetByoipPrefixes sets the ByoipPrefixes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesListResponse) SetByoipPrefixes(byoipPrefixes []*ByoipPrefix) {
	b.ByoipPrefixes = byoipPrefixes
	b.require(byoipPrefixesListResponseFieldByoipPrefixes)
}

func (b *ByoipPrefixesListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ByoipPrefixesListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = ByoipPrefixesListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *ByoipPrefixesListResponse) MarshalJSON() ([]byte, error) {
	type embed ByoipPrefixesListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *ByoipPrefixesListResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	byoipPrefixesPatchResponseFieldByoipPrefix = big.NewInt(1 << 0)
)

type ByoipPrefixesPatchResponse struct {
	ByoipPrefix *ByoipPrefix `json:"byoip_prefix,omitempty" url:"byoip_prefix,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *ByoipPrefixesPatchResponse) GetByoipPrefix() *ByoipPrefix {
	if b == nil {
		return nil
	}
	return b.ByoipPrefix
}

func (b *ByoipPrefixesPatchResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *ByoipPrefixesPatchResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetByoipPrefix sets the ByoipPrefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *ByoipPrefixesPatchResponse) SetByoipPrefix(byoipPrefix *ByoipPrefix) {
	b.ByoipPrefix = byoipPrefix
	b.require(byoipPrefixesPatchResponseFieldByoipPrefix)
}

func (b *ByoipPrefixesPatchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ByoipPrefixesPatchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = ByoipPrefixesPatchResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *ByoipPrefixesPatchResponse) MarshalJSON() ([]byte, error) {
	type embed ByoipPrefixesPatchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *ByoipPrefixesPatchResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}
