// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	core "github.com/harshmaru7/godo-next/core"
)

// There was an error parsing the request body.
type BadRequestError struct {
	*core.APIError
	Body any
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// The request could not be completed due to a conflict.
type ConflictError struct {
	*core.APIError
	Body *Error
}

func (c *ConflictError) UnmarshalJSON(data []byte) error {
	var body *Error
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.StatusCode = 409
	c.Body = body
	return nil
}

func (c *ConflictError) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

func (c *ConflictError) Unwrap() error {
	return c.APIError
}

// Not Allowed.
type ForbiddenError struct {
	*core.APIError
	Body any
}

func (f *ForbiddenError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	f.StatusCode = 403
	f.Body = body
	return nil
}

func (f *ForbiddenError) MarshalJSON() ([]byte, error) {
	return json.Marshal(f.Body)
}

func (f *ForbiddenError) Unwrap() error {
	return f.APIError
}

// There was a server error.
type InternalServerError struct {
	*core.APIError
	Body *Error
}

func (i *InternalServerError) UnmarshalJSON(data []byte) error {
	var body *Error
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.StatusCode = 500
	i.Body = body
	return nil
}

func (i *InternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

func (i *InternalServerError) Unwrap() error {
	return i.APIError
}

// The resource was not found.
type NotFoundError struct {
	*core.APIError
	Body *Error
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	var body *Error
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

// Only an empty project can be deleted.
type PreconditionFailedError struct {
	*core.APIError
	Body *Error
}

func (p *PreconditionFailedError) UnmarshalJSON(data []byte) error {
	var body *Error
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.StatusCode = 412
	p.Body = body
	return nil
}

func (p *PreconditionFailedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

func (p *PreconditionFailedError) Unwrap() error {
	return p.APIError
}

// The API rate limit has been exceeded.
type TooManyRequestsError struct {
	*core.APIError
	Body *Error
}

func (t *TooManyRequestsError) UnmarshalJSON(data []byte) error {
	var body *Error
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.StatusCode = 429
	t.Body = body
	return nil
}

func (t *TooManyRequestsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

func (t *TooManyRequestsError) Unwrap() error {
	return t.APIError
}

// Authentication failed due to invalid credentials.
type UnauthorizedError struct {
	*core.APIError
	Body *Error
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body *Error
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}

// Unprocessable Entity
type UnprocessableEntityError struct {
	*core.APIError
	Body *Error
}

func (u *UnprocessableEntityError) UnmarshalJSON(data []byte) error {
	var body *Error
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 422
	u.Body = body
	return nil
}

func (u *UnprocessableEntityError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnprocessableEntityError) Unwrap() error {
	return u.APIError
}
