// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/harshmaru7/godo-next/internal"
	big "math/big"
)

var (
	floatingIPsDeleteRequestFieldFloatingIP = big.NewInt(1 << 0)
)

type FloatingIPsDeleteRequest struct {
	// A floating IP address.
	FloatingIP string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FloatingIPsDeleteRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetFloatingIP sets the FloatingIP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsDeleteRequest) SetFloatingIP(floatingIP string) {
	f.FloatingIP = floatingIP
	f.require(floatingIPsDeleteRequestFieldFloatingIP)
}

var (
	floatingIPsGetRequestFieldFloatingIP = big.NewInt(1 << 0)
)

type FloatingIPsGetRequest struct {
	// A floating IP address.
	FloatingIP string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FloatingIPsGetRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetFloatingIP sets the FloatingIP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsGetRequest) SetFloatingIP(floatingIP string) {
	f.FloatingIP = floatingIP
	f.require(floatingIPsGetRequestFieldFloatingIP)
}

var (
	floatingIPsListRequestFieldPerPage = big.NewInt(1 << 0)
	floatingIPsListRequestFieldPage    = big.NewInt(1 << 1)
)

type FloatingIPsListRequest struct {
	// Number of items returned per page
	PerPage *int `json:"-" url:"per_page,omitempty"`
	// Which 'page' of paginated results to return.
	Page *int `json:"-" url:"page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FloatingIPsListRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsListRequest) SetPerPage(perPage *int) {
	f.PerPage = perPage
	f.require(floatingIPsListRequestFieldPerPage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsListRequest) SetPage(page *int) {
	f.Page = page
	f.require(floatingIPsListRequestFieldPage)
}

var (
	floatingIPFieldIP        = big.NewInt(1 << 0)
	floatingIPFieldRegion    = big.NewInt(1 << 1)
	floatingIPFieldDroplet   = big.NewInt(1 << 2)
	floatingIPFieldLocked    = big.NewInt(1 << 3)
	floatingIPFieldProjectID = big.NewInt(1 << 4)
)

type FloatingIP struct {
	// The public IP address of the floating IP. It also serves as its identifier.
	IP     *string           `json:"ip,omitempty" url:"ip,omitempty"`
	Region *FloatingIPRegion `json:"region,omitempty" url:"region,omitempty"`
	// The Droplet that the floating IP has been assigned to. When you query a floating IP, if it is assigned to a Droplet, the entire Droplet object will be returned. If it is not assigned, the value will be null. <br><br>Requires `droplet:read` scope.
	Droplet *FloatingIPDroplet `json:"droplet,omitempty" url:"droplet,omitempty"`
	// A boolean value indicating whether or not the floating IP has pending actions preventing new ones from being submitted.
	Locked *bool `json:"locked,omitempty" url:"locked,omitempty"`
	// The UUID of the project to which the reserved IP currently belongs.<br><br>Requires `project:read` scope.
	ProjectID *string `json:"project_id,omitempty" url:"project_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FloatingIP) GetIP() *string {
	if f == nil {
		return nil
	}
	return f.IP
}

func (f *FloatingIP) GetRegion() *FloatingIPRegion {
	if f == nil {
		return nil
	}
	return f.Region
}

func (f *FloatingIP) GetDroplet() *FloatingIPDroplet {
	if f == nil {
		return nil
	}
	return f.Droplet
}

func (f *FloatingIP) GetLocked() *bool {
	if f == nil {
		return nil
	}
	return f.Locked
}

func (f *FloatingIP) GetProjectID() *string {
	if f == nil {
		return nil
	}
	return f.ProjectID
}

func (f *FloatingIP) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FloatingIP) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetIP sets the IP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIP) SetIP(ip *string) {
	f.IP = ip
	f.require(floatingIPFieldIP)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIP) SetRegion(region *FloatingIPRegion) {
	f.Region = region
	f.require(floatingIPFieldRegion)
}

// SetDroplet sets the Droplet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIP) SetDroplet(droplet *FloatingIPDroplet) {
	f.Droplet = droplet
	f.require(floatingIPFieldDroplet)
}

// SetLocked sets the Locked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIP) SetLocked(locked *bool) {
	f.Locked = locked
	f.require(floatingIPFieldLocked)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIP) SetProjectID(projectID *string) {
	f.ProjectID = projectID
	f.require(floatingIPFieldProjectID)
}

func (f *FloatingIP) UnmarshalJSON(data []byte) error {
	type unmarshaler FloatingIP
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FloatingIP(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FloatingIP) MarshalJSON() ([]byte, error) {
	type embed FloatingIP
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FloatingIP) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type FloatingIPCreate struct {
	FloatingIPCreateDropletID *FloatingIPCreateDropletID
	FloatingIPCreateProjectID *FloatingIPCreateProjectID

	typ string
}

func (f *FloatingIPCreate) GetFloatingIPCreateDropletID() *FloatingIPCreateDropletID {
	if f == nil {
		return nil
	}
	return f.FloatingIPCreateDropletID
}

func (f *FloatingIPCreate) GetFloatingIPCreateProjectID() *FloatingIPCreateProjectID {
	if f == nil {
		return nil
	}
	return f.FloatingIPCreateProjectID
}

func (f *FloatingIPCreate) UnmarshalJSON(data []byte) error {
	valueFloatingIPCreateDropletID := new(FloatingIPCreateDropletID)
	if err := json.Unmarshal(data, &valueFloatingIPCreateDropletID); err == nil {
		f.typ = "FloatingIPCreateDropletID"
		f.FloatingIPCreateDropletID = valueFloatingIPCreateDropletID
		return nil
	}
	valueFloatingIPCreateProjectID := new(FloatingIPCreateProjectID)
	if err := json.Unmarshal(data, &valueFloatingIPCreateProjectID); err == nil {
		f.typ = "FloatingIPCreateProjectID"
		f.FloatingIPCreateProjectID = valueFloatingIPCreateProjectID
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, f)
}

func (f FloatingIPCreate) MarshalJSON() ([]byte, error) {
	if f.typ == "FloatingIPCreateDropletID" || f.FloatingIPCreateDropletID != nil {
		return json.Marshal(f.FloatingIPCreateDropletID)
	}
	if f.typ == "FloatingIPCreateProjectID" || f.FloatingIPCreateProjectID != nil {
		return json.Marshal(f.FloatingIPCreateProjectID)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", f)
}

type FloatingIPCreateVisitor interface {
	VisitFloatingIPCreateDropletID(*FloatingIPCreateDropletID) error
	VisitFloatingIPCreateProjectID(*FloatingIPCreateProjectID) error
}

func (f *FloatingIPCreate) Accept(visitor FloatingIPCreateVisitor) error {
	if f.typ == "FloatingIPCreateDropletID" || f.FloatingIPCreateDropletID != nil {
		return visitor.VisitFloatingIPCreateDropletID(f.FloatingIPCreateDropletID)
	}
	if f.typ == "FloatingIPCreateProjectID" || f.FloatingIPCreateProjectID != nil {
		return visitor.VisitFloatingIPCreateProjectID(f.FloatingIPCreateProjectID)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", f)
}

var (
	floatingIPCreateDropletIDFieldDropletID = big.NewInt(1 << 0)
)

type FloatingIPCreateDropletID struct {
	// The ID of the Droplet that the floating IP will be assigned to.
	DropletID int `json:"droplet_id" url:"droplet_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FloatingIPCreateDropletID) GetDropletID() int {
	if f == nil {
		return 0
	}
	return f.DropletID
}

func (f *FloatingIPCreateDropletID) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FloatingIPCreateDropletID) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetDropletID sets the DropletID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPCreateDropletID) SetDropletID(dropletID int) {
	f.DropletID = dropletID
	f.require(floatingIPCreateDropletIDFieldDropletID)
}

func (f *FloatingIPCreateDropletID) UnmarshalJSON(data []byte) error {
	type unmarshaler FloatingIPCreateDropletID
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FloatingIPCreateDropletID(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FloatingIPCreateDropletID) MarshalJSON() ([]byte, error) {
	type embed FloatingIPCreateDropletID
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FloatingIPCreateDropletID) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	floatingIPCreateProjectIDFieldRegion    = big.NewInt(1 << 0)
	floatingIPCreateProjectIDFieldProjectID = big.NewInt(1 << 1)
)

type FloatingIPCreateProjectID struct {
	// The slug identifier for the region the floating IP will be reserved to.
	Region string `json:"region" url:"region"`
	// The UUID of the project to which the floating IP will be assigned.
	ProjectID *string `json:"project_id,omitempty" url:"project_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FloatingIPCreateProjectID) GetRegion() string {
	if f == nil {
		return ""
	}
	return f.Region
}

func (f *FloatingIPCreateProjectID) GetProjectID() *string {
	if f == nil {
		return nil
	}
	return f.ProjectID
}

func (f *FloatingIPCreateProjectID) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FloatingIPCreateProjectID) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPCreateProjectID) SetRegion(region string) {
	f.Region = region
	f.require(floatingIPCreateProjectIDFieldRegion)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPCreateProjectID) SetProjectID(projectID *string) {
	f.ProjectID = projectID
	f.require(floatingIPCreateProjectIDFieldProjectID)
}

func (f *FloatingIPCreateProjectID) UnmarshalJSON(data []byte) error {
	type unmarshaler FloatingIPCreateProjectID
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FloatingIPCreateProjectID(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FloatingIPCreateProjectID) MarshalJSON() ([]byte, error) {
	type embed FloatingIPCreateProjectID
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FloatingIPCreateProjectID) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// The Droplet that the floating IP has been assigned to. When you query a floating IP, if it is assigned to a Droplet, the entire Droplet object will be returned. If it is not assigned, the value will be null. <br><br>Requires `droplet:read` scope.
type FloatingIPDroplet struct {
	// If the floating IP is not assigned to a Droplet, the value will be null.
	StringUnknownMapOptional map[string]any
	Droplet                  *Droplet

	typ string
}

func (f *FloatingIPDroplet) GetStringUnknownMapOptional() map[string]any {
	if f == nil {
		return nil
	}
	return f.StringUnknownMapOptional
}

func (f *FloatingIPDroplet) GetDroplet() *Droplet {
	if f == nil {
		return nil
	}
	return f.Droplet
}

func (f *FloatingIPDroplet) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMapOptional map[string]any
	if err := json.Unmarshal(data, &valueStringUnknownMapOptional); err == nil {
		f.typ = "StringUnknownMapOptional"
		f.StringUnknownMapOptional = valueStringUnknownMapOptional
		return nil
	}
	valueDroplet := new(Droplet)
	if err := json.Unmarshal(data, &valueDroplet); err == nil {
		f.typ = "Droplet"
		f.Droplet = valueDroplet
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, f)
}

func (f FloatingIPDroplet) MarshalJSON() ([]byte, error) {
	if f.typ == "StringUnknownMapOptional" || f.StringUnknownMapOptional != nil {
		return json.Marshal(f.StringUnknownMapOptional)
	}
	if f.typ == "Droplet" || f.Droplet != nil {
		return json.Marshal(f.Droplet)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", f)
}

type FloatingIPDropletVisitor interface {
	VisitStringUnknownMapOptional(map[string]any) error
	VisitDroplet(*Droplet) error
}

func (f *FloatingIPDroplet) Accept(visitor FloatingIPDropletVisitor) error {
	if f.typ == "StringUnknownMapOptional" || f.StringUnknownMapOptional != nil {
		return visitor.VisitStringUnknownMapOptional(f.StringUnknownMapOptional)
	}
	if f.typ == "Droplet" || f.Droplet != nil {
		return visitor.VisitDroplet(f.Droplet)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", f)
}

var (
	floatingIPRegionFieldName      = big.NewInt(1 << 0)
	floatingIPRegionFieldSlug      = big.NewInt(1 << 1)
	floatingIPRegionFieldFeatures  = big.NewInt(1 << 2)
	floatingIPRegionFieldAvailable = big.NewInt(1 << 3)
	floatingIPRegionFieldSizes     = big.NewInt(1 << 4)
)

type FloatingIPRegion struct {
	// The display name of the region.  This will be a full name that is used in the control panel and other interfaces.
	Name string `json:"name" url:"name"`
	// A human-readable string that is used as a unique identifier for each region.
	Slug string `json:"slug" url:"slug"`
	// This attribute is set to an array which contains features available in this region
	Features []string `json:"features" url:"features"`
	// This is a boolean value that represents whether new Droplets can be created in this region.
	Available bool `json:"available" url:"available"`
	// This attribute is set to an array which contains the identifying slugs for the sizes available in this region. sizes:read is required to view.
	Sizes []string `json:"sizes" url:"sizes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FloatingIPRegion) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FloatingIPRegion) GetSlug() string {
	if f == nil {
		return ""
	}
	return f.Slug
}

func (f *FloatingIPRegion) GetFeatures() []string {
	if f == nil {
		return nil
	}
	return f.Features
}

func (f *FloatingIPRegion) GetAvailable() bool {
	if f == nil {
		return false
	}
	return f.Available
}

func (f *FloatingIPRegion) GetSizes() []string {
	if f == nil {
		return nil
	}
	return f.Sizes
}

func (f *FloatingIPRegion) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FloatingIPRegion) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPRegion) SetName(name string) {
	f.Name = name
	f.require(floatingIPRegionFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPRegion) SetSlug(slug string) {
	f.Slug = slug
	f.require(floatingIPRegionFieldSlug)
}

// SetFeatures sets the Features field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPRegion) SetFeatures(features []string) {
	f.Features = features
	f.require(floatingIPRegionFieldFeatures)
}

// SetAvailable sets the Available field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPRegion) SetAvailable(available bool) {
	f.Available = available
	f.require(floatingIPRegionFieldAvailable)
}

// SetSizes sets the Sizes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPRegion) SetSizes(sizes []string) {
	f.Sizes = sizes
	f.require(floatingIPRegionFieldSizes)
}

func (f *FloatingIPRegion) UnmarshalJSON(data []byte) error {
	type unmarshaler FloatingIPRegion
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FloatingIPRegion(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FloatingIPRegion) MarshalJSON() ([]byte, error) {
	type embed FloatingIPRegion
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FloatingIPRegion) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	floatingIPsCreateResponseFieldFloatingIP = big.NewInt(1 << 0)
	floatingIPsCreateResponseFieldLinks      = big.NewInt(1 << 1)
)

type FloatingIPsCreateResponse struct {
	FloatingIP *FloatingIP                     `json:"floating_ip,omitempty" url:"floating_ip,omitempty"`
	Links      *FloatingIPsCreateResponseLinks `json:"links,omitempty" url:"links,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FloatingIPsCreateResponse) GetFloatingIP() *FloatingIP {
	if f == nil {
		return nil
	}
	return f.FloatingIP
}

func (f *FloatingIPsCreateResponse) GetLinks() *FloatingIPsCreateResponseLinks {
	if f == nil {
		return nil
	}
	return f.Links
}

func (f *FloatingIPsCreateResponse) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FloatingIPsCreateResponse) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetFloatingIP sets the FloatingIP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsCreateResponse) SetFloatingIP(floatingIP *FloatingIP) {
	f.FloatingIP = floatingIP
	f.require(floatingIPsCreateResponseFieldFloatingIP)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsCreateResponse) SetLinks(links *FloatingIPsCreateResponseLinks) {
	f.Links = links
	f.require(floatingIPsCreateResponseFieldLinks)
}

func (f *FloatingIPsCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler FloatingIPsCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FloatingIPsCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FloatingIPsCreateResponse) MarshalJSON() ([]byte, error) {
	type embed FloatingIPsCreateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FloatingIPsCreateResponse) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	floatingIPsCreateResponseLinksFieldDroplets = big.NewInt(1 << 0)
	floatingIPsCreateResponseLinksFieldActions  = big.NewInt(1 << 1)
)

type FloatingIPsCreateResponseLinks struct {
	Droplets []*ActionLink `json:"droplets,omitempty" url:"droplets,omitempty"`
	Actions  []*ActionLink `json:"actions,omitempty" url:"actions,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FloatingIPsCreateResponseLinks) GetDroplets() []*ActionLink {
	if f == nil {
		return nil
	}
	return f.Droplets
}

func (f *FloatingIPsCreateResponseLinks) GetActions() []*ActionLink {
	if f == nil {
		return nil
	}
	return f.Actions
}

func (f *FloatingIPsCreateResponseLinks) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FloatingIPsCreateResponseLinks) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetDroplets sets the Droplets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsCreateResponseLinks) SetDroplets(droplets []*ActionLink) {
	f.Droplets = droplets
	f.require(floatingIPsCreateResponseLinksFieldDroplets)
}

// SetActions sets the Actions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsCreateResponseLinks) SetActions(actions []*ActionLink) {
	f.Actions = actions
	f.require(floatingIPsCreateResponseLinksFieldActions)
}

func (f *FloatingIPsCreateResponseLinks) UnmarshalJSON(data []byte) error {
	type unmarshaler FloatingIPsCreateResponseLinks
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FloatingIPsCreateResponseLinks(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FloatingIPsCreateResponseLinks) MarshalJSON() ([]byte, error) {
	type embed FloatingIPsCreateResponseLinks
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FloatingIPsCreateResponseLinks) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	floatingIPsGetResponseFieldFloatingIP = big.NewInt(1 << 0)
)

type FloatingIPsGetResponse struct {
	FloatingIP *FloatingIP `json:"floating_ip,omitempty" url:"floating_ip,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FloatingIPsGetResponse) GetFloatingIP() *FloatingIP {
	if f == nil {
		return nil
	}
	return f.FloatingIP
}

func (f *FloatingIPsGetResponse) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FloatingIPsGetResponse) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetFloatingIP sets the FloatingIP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsGetResponse) SetFloatingIP(floatingIP *FloatingIP) {
	f.FloatingIP = floatingIP
	f.require(floatingIPsGetResponseFieldFloatingIP)
}

func (f *FloatingIPsGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler FloatingIPsGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FloatingIPsGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FloatingIPsGetResponse) MarshalJSON() ([]byte, error) {
	type embed FloatingIPsGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FloatingIPsGetResponse) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	floatingIPsListResponseFieldLinks       = big.NewInt(1 << 0)
	floatingIPsListResponseFieldMeta        = big.NewInt(1 << 1)
	floatingIPsListResponseFieldFloatingIps = big.NewInt(1 << 2)
)

type FloatingIPsListResponse struct {
	Links *PageLinks `json:"links,omitempty" url:"links,omitempty"`
	// Information about the response itself.
	Meta        *MetaMeta     `json:"meta" url:"meta"`
	FloatingIps []*FloatingIP `json:"floating_ips,omitempty" url:"floating_ips,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FloatingIPsListResponse) GetLinks() *PageLinks {
	if f == nil {
		return nil
	}
	return f.Links
}

func (f *FloatingIPsListResponse) GetMeta() *MetaMeta {
	if f == nil {
		return nil
	}
	return f.Meta
}

func (f *FloatingIPsListResponse) GetFloatingIps() []*FloatingIP {
	if f == nil {
		return nil
	}
	return f.FloatingIps
}

func (f *FloatingIPsListResponse) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FloatingIPsListResponse) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsListResponse) SetLinks(links *PageLinks) {
	f.Links = links
	f.require(floatingIPsListResponseFieldLinks)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsListResponse) SetMeta(meta *MetaMeta) {
	f.Meta = meta
	f.require(floatingIPsListResponseFieldMeta)
}

// SetFloatingIps sets the FloatingIps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FloatingIPsListResponse) SetFloatingIps(floatingIps []*FloatingIP) {
	f.FloatingIps = floatingIps
	f.require(floatingIPsListResponseFieldFloatingIps)
}

func (f *FloatingIPsListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler FloatingIPsListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FloatingIPsListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FloatingIPsListResponse) MarshalJSON() ([]byte, error) {
	type embed FloatingIPsListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FloatingIPsListResponse) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}
