// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/harshmaru7/godo-next/internal"
	big "math/big"
	time "time"
)

var (
	reservedIpv6CreateFieldRegionSlug = big.NewInt(1 << 0)
)

type ReservedIpv6Create struct {
	// The slug identifier for the region the reserved IPv6 will be reserved to.
	RegionSlug string `json:"region_slug" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReservedIpv6Create) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRegionSlug sets the RegionSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIpv6Create) SetRegionSlug(regionSlug string) {
	r.RegionSlug = regionSlug
	r.require(reservedIpv6CreateFieldRegionSlug)
}

func (r *ReservedIpv6Create) UnmarshalJSON(data []byte) error {
	type unmarshaler ReservedIpv6Create
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = ReservedIpv6Create(body)
	return nil
}

func (r *ReservedIpv6Create) MarshalJSON() ([]byte, error) {
	type embed ReservedIpv6Create
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	reservedIPv6DeleteRequestFieldReservedIpv6 = big.NewInt(1 << 0)
)

type ReservedIPv6DeleteRequest struct {
	// A reserved IPv6 address.
	ReservedIpv6 string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReservedIPv6DeleteRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetReservedIpv6 sets the ReservedIpv6 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6DeleteRequest) SetReservedIpv6(reservedIpv6 string) {
	r.ReservedIpv6 = reservedIpv6
	r.require(reservedIPv6DeleteRequestFieldReservedIpv6)
}

var (
	reservedIPv6GetRequestFieldReservedIpv6 = big.NewInt(1 << 0)
)

type ReservedIPv6GetRequest struct {
	// A reserved IPv6 address.
	ReservedIpv6 string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReservedIPv6GetRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetReservedIpv6 sets the ReservedIpv6 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6GetRequest) SetReservedIpv6(reservedIpv6 string) {
	r.ReservedIpv6 = reservedIpv6
	r.require(reservedIPv6GetRequestFieldReservedIpv6)
}

var (
	reservedIPv6ListRequestFieldPerPage = big.NewInt(1 << 0)
	reservedIPv6ListRequestFieldPage    = big.NewInt(1 << 1)
)

type ReservedIPv6ListRequest struct {
	// Number of items returned per page
	PerPage *int `json:"-" url:"per_page,omitempty"`
	// Which 'page' of paginated results to return.
	Page *int `json:"-" url:"page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReservedIPv6ListRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6ListRequest) SetPerPage(perPage *int) {
	r.PerPage = perPage
	r.require(reservedIPv6ListRequestFieldPerPage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6ListRequest) SetPage(page *int) {
	r.Page = page
	r.require(reservedIPv6ListRequestFieldPage)
}

var (
	reservedIpv6FieldIP         = big.NewInt(1 << 0)
	reservedIpv6FieldReservedAt = big.NewInt(1 << 1)
	reservedIpv6FieldRegionSlug = big.NewInt(1 << 2)
	reservedIpv6FieldDroplet    = big.NewInt(1 << 3)
)

type ReservedIpv6 struct {
	// The public IP address of the reserved IPv6. It also serves as its identifier.
	IP *string `json:"ip,omitempty" url:"ip,omitempty"`
	// The date and time when the reserved IPv6 was reserved.
	ReservedAt *time.Time `json:"reserved_at,omitempty" url:"reserved_at,omitempty"`
	// The region that the reserved IPv6 is reserved to. When you query a reserved IPv6,the region_slug will be returned.
	RegionSlug *string              `json:"region_slug,omitempty" url:"region_slug,omitempty"`
	Droplet    *ReservedIpv6Droplet `json:"droplet,omitempty" url:"droplet,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReservedIpv6) GetIP() *string {
	if r == nil {
		return nil
	}
	return r.IP
}

func (r *ReservedIpv6) GetReservedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.ReservedAt
}

func (r *ReservedIpv6) GetRegionSlug() *string {
	if r == nil {
		return nil
	}
	return r.RegionSlug
}

func (r *ReservedIpv6) GetDroplet() *ReservedIpv6Droplet {
	if r == nil {
		return nil
	}
	return r.Droplet
}

func (r *ReservedIpv6) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReservedIpv6) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetIP sets the IP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIpv6) SetIP(ip *string) {
	r.IP = ip
	r.require(reservedIpv6FieldIP)
}

// SetReservedAt sets the ReservedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIpv6) SetReservedAt(reservedAt *time.Time) {
	r.ReservedAt = reservedAt
	r.require(reservedIpv6FieldReservedAt)
}

// SetRegionSlug sets the RegionSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIpv6) SetRegionSlug(regionSlug *string) {
	r.RegionSlug = regionSlug
	r.require(reservedIpv6FieldRegionSlug)
}

// SetDroplet sets the Droplet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIpv6) SetDroplet(droplet *ReservedIpv6Droplet) {
	r.Droplet = droplet
	r.require(reservedIpv6FieldDroplet)
}

func (r *ReservedIpv6) UnmarshalJSON(data []byte) error {
	type embed ReservedIpv6
	var unmarshaler = struct {
		embed
		ReservedAt *internal.DateTime `json:"reserved_at,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = ReservedIpv6(unmarshaler.embed)
	r.ReservedAt = unmarshaler.ReservedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReservedIpv6) MarshalJSON() ([]byte, error) {
	type embed ReservedIpv6
	var marshaler = struct {
		embed
		ReservedAt *internal.DateTime `json:"reserved_at,omitempty"`
	}{
		embed:      embed(*r),
		ReservedAt: internal.NewOptionalDateTime(r.ReservedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReservedIpv6) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReservedIpv6Droplet struct {
	// If the reserved IP is not assigned to a Droplet, the value will be null.<br><br>Requires `droplet:read` scope.
	StringUnknownMapOptional map[string]any
	Droplet                  *Droplet

	typ string
}

func (r *ReservedIpv6Droplet) GetStringUnknownMapOptional() map[string]any {
	if r == nil {
		return nil
	}
	return r.StringUnknownMapOptional
}

func (r *ReservedIpv6Droplet) GetDroplet() *Droplet {
	if r == nil {
		return nil
	}
	return r.Droplet
}

func (r *ReservedIpv6Droplet) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMapOptional map[string]any
	if err := json.Unmarshal(data, &valueStringUnknownMapOptional); err == nil {
		r.typ = "StringUnknownMapOptional"
		r.StringUnknownMapOptional = valueStringUnknownMapOptional
		return nil
	}
	valueDroplet := new(Droplet)
	if err := json.Unmarshal(data, &valueDroplet); err == nil {
		r.typ = "Droplet"
		r.Droplet = valueDroplet
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, r)
}

func (r ReservedIpv6Droplet) MarshalJSON() ([]byte, error) {
	if r.typ == "StringUnknownMapOptional" || r.StringUnknownMapOptional != nil {
		return json.Marshal(r.StringUnknownMapOptional)
	}
	if r.typ == "Droplet" || r.Droplet != nil {
		return json.Marshal(r.Droplet)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", r)
}

type ReservedIpv6DropletVisitor interface {
	VisitStringUnknownMapOptional(map[string]any) error
	VisitDroplet(*Droplet) error
}

func (r *ReservedIpv6Droplet) Accept(visitor ReservedIpv6DropletVisitor) error {
	if r.typ == "StringUnknownMapOptional" || r.StringUnknownMapOptional != nil {
		return visitor.VisitStringUnknownMapOptional(r.StringUnknownMapOptional)
	}
	if r.typ == "Droplet" || r.Droplet != nil {
		return visitor.VisitDroplet(r.Droplet)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", r)
}

var (
	reservedIpv6ListFieldReservedIpv6S = big.NewInt(1 << 0)
)

type ReservedIpv6List struct {
	ReservedIpv6S []*ReservedIpv6ListReservedIpv6SItem `json:"reserved_ipv6s,omitempty" url:"reserved_ipv6s,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReservedIpv6List) GetReservedIpv6S() []*ReservedIpv6ListReservedIpv6SItem {
	if r == nil {
		return nil
	}
	return r.ReservedIpv6S
}

func (r *ReservedIpv6List) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReservedIpv6List) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetReservedIpv6S sets the ReservedIpv6S field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIpv6List) SetReservedIpv6S(reservedIpv6S []*ReservedIpv6ListReservedIpv6SItem) {
	r.ReservedIpv6S = reservedIpv6S
	r.require(reservedIpv6ListFieldReservedIpv6S)
}

func (r *ReservedIpv6List) UnmarshalJSON(data []byte) error {
	type unmarshaler ReservedIpv6List
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReservedIpv6List(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReservedIpv6List) MarshalJSON() ([]byte, error) {
	type embed ReservedIpv6List
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReservedIpv6List) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	reservedIpv6ListReservedIpv6SItemFieldIP         = big.NewInt(1 << 0)
	reservedIpv6ListReservedIpv6SItemFieldRegionSlug = big.NewInt(1 << 1)
	reservedIpv6ListReservedIpv6SItemFieldReservedAt = big.NewInt(1 << 2)
	reservedIpv6ListReservedIpv6SItemFieldDroplet    = big.NewInt(1 << 3)
)

type ReservedIpv6ListReservedIpv6SItem struct {
	// The public IP address of the reserved IPv6. It also serves as its identifier.
	IP *string `json:"ip,omitempty" url:"ip,omitempty"`
	// The region that the reserved IPv6 is reserved to. When you query a reserved IPv6,the region_slug will be returned.
	RegionSlug *string    `json:"region_slug,omitempty" url:"region_slug,omitempty"`
	ReservedAt *time.Time `json:"reserved_at,omitempty" url:"reserved_at,omitempty"`
	// Requires `droplet:read` scope.
	Droplet *ReservedIpv6ListReservedIpv6SItemDroplet `json:"droplet,omitempty" url:"droplet,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReservedIpv6ListReservedIpv6SItem) GetIP() *string {
	if r == nil {
		return nil
	}
	return r.IP
}

func (r *ReservedIpv6ListReservedIpv6SItem) GetRegionSlug() *string {
	if r == nil {
		return nil
	}
	return r.RegionSlug
}

func (r *ReservedIpv6ListReservedIpv6SItem) GetReservedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.ReservedAt
}

func (r *ReservedIpv6ListReservedIpv6SItem) GetDroplet() *ReservedIpv6ListReservedIpv6SItemDroplet {
	if r == nil {
		return nil
	}
	return r.Droplet
}

func (r *ReservedIpv6ListReservedIpv6SItem) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReservedIpv6ListReservedIpv6SItem) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetIP sets the IP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIpv6ListReservedIpv6SItem) SetIP(ip *string) {
	r.IP = ip
	r.require(reservedIpv6ListReservedIpv6SItemFieldIP)
}

// SetRegionSlug sets the RegionSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIpv6ListReservedIpv6SItem) SetRegionSlug(regionSlug *string) {
	r.RegionSlug = regionSlug
	r.require(reservedIpv6ListReservedIpv6SItemFieldRegionSlug)
}

// SetReservedAt sets the ReservedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIpv6ListReservedIpv6SItem) SetReservedAt(reservedAt *time.Time) {
	r.ReservedAt = reservedAt
	r.require(reservedIpv6ListReservedIpv6SItemFieldReservedAt)
}

// SetDroplet sets the Droplet field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIpv6ListReservedIpv6SItem) SetDroplet(droplet *ReservedIpv6ListReservedIpv6SItemDroplet) {
	r.Droplet = droplet
	r.require(reservedIpv6ListReservedIpv6SItemFieldDroplet)
}

func (r *ReservedIpv6ListReservedIpv6SItem) UnmarshalJSON(data []byte) error {
	type embed ReservedIpv6ListReservedIpv6SItem
	var unmarshaler = struct {
		embed
		ReservedAt *internal.DateTime `json:"reserved_at,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = ReservedIpv6ListReservedIpv6SItem(unmarshaler.embed)
	r.ReservedAt = unmarshaler.ReservedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReservedIpv6ListReservedIpv6SItem) MarshalJSON() ([]byte, error) {
	type embed ReservedIpv6ListReservedIpv6SItem
	var marshaler = struct {
		embed
		ReservedAt *internal.DateTime `json:"reserved_at,omitempty"`
	}{
		embed:      embed(*r),
		ReservedAt: internal.NewOptionalDateTime(r.ReservedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReservedIpv6ListReservedIpv6SItem) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Requires `droplet:read` scope.
type ReservedIpv6ListReservedIpv6SItemDroplet struct {
	// If the reserved IP is not assigned to a Droplet, the value will be null.<br><br>Requires `droplet:read` scope.
	StringUnknownMapOptional map[string]any
	Droplet                  *Droplet

	typ string
}

func (r *ReservedIpv6ListReservedIpv6SItemDroplet) GetStringUnknownMapOptional() map[string]any {
	if r == nil {
		return nil
	}
	return r.StringUnknownMapOptional
}

func (r *ReservedIpv6ListReservedIpv6SItemDroplet) GetDroplet() *Droplet {
	if r == nil {
		return nil
	}
	return r.Droplet
}

func (r *ReservedIpv6ListReservedIpv6SItemDroplet) UnmarshalJSON(data []byte) error {
	var valueStringUnknownMapOptional map[string]any
	if err := json.Unmarshal(data, &valueStringUnknownMapOptional); err == nil {
		r.typ = "StringUnknownMapOptional"
		r.StringUnknownMapOptional = valueStringUnknownMapOptional
		return nil
	}
	valueDroplet := new(Droplet)
	if err := json.Unmarshal(data, &valueDroplet); err == nil {
		r.typ = "Droplet"
		r.Droplet = valueDroplet
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, r)
}

func (r ReservedIpv6ListReservedIpv6SItemDroplet) MarshalJSON() ([]byte, error) {
	if r.typ == "StringUnknownMapOptional" || r.StringUnknownMapOptional != nil {
		return json.Marshal(r.StringUnknownMapOptional)
	}
	if r.typ == "Droplet" || r.Droplet != nil {
		return json.Marshal(r.Droplet)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", r)
}

type ReservedIpv6ListReservedIpv6SItemDropletVisitor interface {
	VisitStringUnknownMapOptional(map[string]any) error
	VisitDroplet(*Droplet) error
}

func (r *ReservedIpv6ListReservedIpv6SItemDroplet) Accept(visitor ReservedIpv6ListReservedIpv6SItemDropletVisitor) error {
	if r.typ == "StringUnknownMapOptional" || r.StringUnknownMapOptional != nil {
		return visitor.VisitStringUnknownMapOptional(r.StringUnknownMapOptional)
	}
	if r.typ == "Droplet" || r.Droplet != nil {
		return visitor.VisitDroplet(r.Droplet)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", r)
}

var (
	reservedIPv6CreateResponseFieldReservedIpv6 = big.NewInt(1 << 0)
)

type ReservedIPv6CreateResponse struct {
	ReservedIpv6 *ReservedIPv6CreateResponseReservedIpv6 `json:"reserved_ipv6,omitempty" url:"reserved_ipv6,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReservedIPv6CreateResponse) GetReservedIpv6() *ReservedIPv6CreateResponseReservedIpv6 {
	if r == nil {
		return nil
	}
	return r.ReservedIpv6
}

func (r *ReservedIPv6CreateResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReservedIPv6CreateResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetReservedIpv6 sets the ReservedIpv6 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6CreateResponse) SetReservedIpv6(reservedIpv6 *ReservedIPv6CreateResponseReservedIpv6) {
	r.ReservedIpv6 = reservedIpv6
	r.require(reservedIPv6CreateResponseFieldReservedIpv6)
}

func (r *ReservedIPv6CreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ReservedIPv6CreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReservedIPv6CreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReservedIPv6CreateResponse) MarshalJSON() ([]byte, error) {
	type embed ReservedIPv6CreateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReservedIPv6CreateResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	reservedIPv6CreateResponseReservedIpv6FieldIP         = big.NewInt(1 << 0)
	reservedIPv6CreateResponseReservedIpv6FieldRegionSlug = big.NewInt(1 << 1)
	reservedIPv6CreateResponseReservedIpv6FieldReservedAt = big.NewInt(1 << 2)
)

type ReservedIPv6CreateResponseReservedIpv6 struct {
	// The public IP address of the reserved IPv6. It also serves as its identifier.
	IP *string `json:"ip,omitempty" url:"ip,omitempty"`
	// The region that the reserved IPv6 is reserved to. When you query a reserved IPv6,the region_slug will be returned.
	RegionSlug *string    `json:"region_slug,omitempty" url:"region_slug,omitempty"`
	ReservedAt *time.Time `json:"reserved_at,omitempty" url:"reserved_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReservedIPv6CreateResponseReservedIpv6) GetIP() *string {
	if r == nil {
		return nil
	}
	return r.IP
}

func (r *ReservedIPv6CreateResponseReservedIpv6) GetRegionSlug() *string {
	if r == nil {
		return nil
	}
	return r.RegionSlug
}

func (r *ReservedIPv6CreateResponseReservedIpv6) GetReservedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.ReservedAt
}

func (r *ReservedIPv6CreateResponseReservedIpv6) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReservedIPv6CreateResponseReservedIpv6) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetIP sets the IP field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6CreateResponseReservedIpv6) SetIP(ip *string) {
	r.IP = ip
	r.require(reservedIPv6CreateResponseReservedIpv6FieldIP)
}

// SetRegionSlug sets the RegionSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6CreateResponseReservedIpv6) SetRegionSlug(regionSlug *string) {
	r.RegionSlug = regionSlug
	r.require(reservedIPv6CreateResponseReservedIpv6FieldRegionSlug)
}

// SetReservedAt sets the ReservedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6CreateResponseReservedIpv6) SetReservedAt(reservedAt *time.Time) {
	r.ReservedAt = reservedAt
	r.require(reservedIPv6CreateResponseReservedIpv6FieldReservedAt)
}

func (r *ReservedIPv6CreateResponseReservedIpv6) UnmarshalJSON(data []byte) error {
	type embed ReservedIPv6CreateResponseReservedIpv6
	var unmarshaler = struct {
		embed
		ReservedAt *internal.DateTime `json:"reserved_at,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = ReservedIPv6CreateResponseReservedIpv6(unmarshaler.embed)
	r.ReservedAt = unmarshaler.ReservedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReservedIPv6CreateResponseReservedIpv6) MarshalJSON() ([]byte, error) {
	type embed ReservedIPv6CreateResponseReservedIpv6
	var marshaler = struct {
		embed
		ReservedAt *internal.DateTime `json:"reserved_at,omitempty"`
	}{
		embed:      embed(*r),
		ReservedAt: internal.NewOptionalDateTime(r.ReservedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReservedIPv6CreateResponseReservedIpv6) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	reservedIPv6GetResponseFieldReservedIpv6 = big.NewInt(1 << 0)
)

type ReservedIPv6GetResponse struct {
	ReservedIpv6 *ReservedIpv6 `json:"reserved_ipv6,omitempty" url:"reserved_ipv6,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReservedIPv6GetResponse) GetReservedIpv6() *ReservedIpv6 {
	if r == nil {
		return nil
	}
	return r.ReservedIpv6
}

func (r *ReservedIPv6GetResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReservedIPv6GetResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetReservedIpv6 sets the ReservedIpv6 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6GetResponse) SetReservedIpv6(reservedIpv6 *ReservedIpv6) {
	r.ReservedIpv6 = reservedIpv6
	r.require(reservedIPv6GetResponseFieldReservedIpv6)
}

func (r *ReservedIPv6GetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ReservedIPv6GetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReservedIPv6GetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReservedIPv6GetResponse) MarshalJSON() ([]byte, error) {
	type embed ReservedIPv6GetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReservedIPv6GetResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	reservedIPv6ListResponseFieldReservedIpv6S = big.NewInt(1 << 0)
	reservedIPv6ListResponseFieldLinks         = big.NewInt(1 << 1)
	reservedIPv6ListResponseFieldMeta          = big.NewInt(1 << 2)
)

type ReservedIPv6ListResponse struct {
	ReservedIpv6S []*ReservedIpv6ListReservedIpv6SItem `json:"reserved_ipv6s,omitempty" url:"reserved_ipv6s,omitempty"`
	Links         *PageLinks                           `json:"links,omitempty" url:"links,omitempty"`
	// Information about the response itself.
	Meta *MetaMeta `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReservedIPv6ListResponse) GetReservedIpv6S() []*ReservedIpv6ListReservedIpv6SItem {
	if r == nil {
		return nil
	}
	return r.ReservedIpv6S
}

func (r *ReservedIPv6ListResponse) GetLinks() *PageLinks {
	if r == nil {
		return nil
	}
	return r.Links
}

func (r *ReservedIPv6ListResponse) GetMeta() *MetaMeta {
	if r == nil {
		return nil
	}
	return r.Meta
}

func (r *ReservedIPv6ListResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReservedIPv6ListResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetReservedIpv6S sets the ReservedIpv6S field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6ListResponse) SetReservedIpv6S(reservedIpv6S []*ReservedIpv6ListReservedIpv6SItem) {
	r.ReservedIpv6S = reservedIpv6S
	r.require(reservedIPv6ListResponseFieldReservedIpv6S)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6ListResponse) SetLinks(links *PageLinks) {
	r.Links = links
	r.require(reservedIPv6ListResponseFieldLinks)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReservedIPv6ListResponse) SetMeta(meta *MetaMeta) {
	r.Meta = meta
	r.require(reservedIPv6ListResponseFieldMeta)
}

func (r *ReservedIPv6ListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ReservedIPv6ListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReservedIPv6ListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReservedIPv6ListResponse) MarshalJSON() ([]byte, error) {
	type embed ReservedIPv6ListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReservedIPv6ListResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
