// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/harshmaru7/godo-next/internal"
	big "math/big"
)

var (
	vpcPeeringsCreateResponseFieldVpcPeering = big.NewInt(1 << 0)
)

type VpcPeeringsCreateResponse struct {
	VpcPeering *VpcPeering `json:"vpc_peering,omitempty" url:"vpc_peering,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VpcPeeringsCreateResponse) GetVpcPeering() *VpcPeering {
	if v == nil {
		return nil
	}
	return v.VpcPeering
}

func (v *VpcPeeringsCreateResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VpcPeeringsCreateResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetVpcPeering sets the VpcPeering field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsCreateResponse) SetVpcPeering(vpcPeering *VpcPeering) {
	v.VpcPeering = vpcPeering
	v.require(vpcPeeringsCreateResponseFieldVpcPeering)
}

func (v *VpcPeeringsCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler VpcPeeringsCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VpcPeeringsCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VpcPeeringsCreateResponse) MarshalJSON() ([]byte, error) {
	type embed VpcPeeringsCreateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VpcPeeringsCreateResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vpcPeeringsDeleteResponseFieldVpcPeering = big.NewInt(1 << 0)
)

type VpcPeeringsDeleteResponse struct {
	VpcPeering *VpcPeering `json:"vpc_peering,omitempty" url:"vpc_peering,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VpcPeeringsDeleteResponse) GetVpcPeering() *VpcPeering {
	if v == nil {
		return nil
	}
	return v.VpcPeering
}

func (v *VpcPeeringsDeleteResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VpcPeeringsDeleteResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetVpcPeering sets the VpcPeering field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsDeleteResponse) SetVpcPeering(vpcPeering *VpcPeering) {
	v.VpcPeering = vpcPeering
	v.require(vpcPeeringsDeleteResponseFieldVpcPeering)
}

func (v *VpcPeeringsDeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler VpcPeeringsDeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VpcPeeringsDeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VpcPeeringsDeleteResponse) MarshalJSON() ([]byte, error) {
	type embed VpcPeeringsDeleteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VpcPeeringsDeleteResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vpcPeeringsGetResponseFieldVpcPeering = big.NewInt(1 << 0)
)

type VpcPeeringsGetResponse struct {
	VpcPeering *VpcPeering `json:"vpc_peering,omitempty" url:"vpc_peering,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VpcPeeringsGetResponse) GetVpcPeering() *VpcPeering {
	if v == nil {
		return nil
	}
	return v.VpcPeering
}

func (v *VpcPeeringsGetResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VpcPeeringsGetResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetVpcPeering sets the VpcPeering field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsGetResponse) SetVpcPeering(vpcPeering *VpcPeering) {
	v.VpcPeering = vpcPeering
	v.require(vpcPeeringsGetResponseFieldVpcPeering)
}

func (v *VpcPeeringsGetResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler VpcPeeringsGetResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VpcPeeringsGetResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VpcPeeringsGetResponse) MarshalJSON() ([]byte, error) {
	type embed VpcPeeringsGetResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VpcPeeringsGetResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vpcPeeringsListResponseFieldLinks       = big.NewInt(1 << 0)
	vpcPeeringsListResponseFieldMeta        = big.NewInt(1 << 1)
	vpcPeeringsListResponseFieldVpcPeerings = big.NewInt(1 << 2)
)

type VpcPeeringsListResponse struct {
	Links *PageLinks `json:"links,omitempty" url:"links,omitempty"`
	// Information about the response itself.
	Meta        *MetaMeta     `json:"meta" url:"meta"`
	VpcPeerings []*VpcPeering `json:"vpc_peerings,omitempty" url:"vpc_peerings,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VpcPeeringsListResponse) GetLinks() *PageLinks {
	if v == nil {
		return nil
	}
	return v.Links
}

func (v *VpcPeeringsListResponse) GetMeta() *MetaMeta {
	if v == nil {
		return nil
	}
	return v.Meta
}

func (v *VpcPeeringsListResponse) GetVpcPeerings() []*VpcPeering {
	if v == nil {
		return nil
	}
	return v.VpcPeerings
}

func (v *VpcPeeringsListResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VpcPeeringsListResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsListResponse) SetLinks(links *PageLinks) {
	v.Links = links
	v.require(vpcPeeringsListResponseFieldLinks)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsListResponse) SetMeta(meta *MetaMeta) {
	v.Meta = meta
	v.require(vpcPeeringsListResponseFieldMeta)
}

// SetVpcPeerings sets the VpcPeerings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsListResponse) SetVpcPeerings(vpcPeerings []*VpcPeering) {
	v.VpcPeerings = vpcPeerings
	v.require(vpcPeeringsListResponseFieldVpcPeerings)
}

func (v *VpcPeeringsListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler VpcPeeringsListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VpcPeeringsListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VpcPeeringsListResponse) MarshalJSON() ([]byte, error) {
	type embed VpcPeeringsListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VpcPeeringsListResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	vpcPeeringsPatchResponseFieldVpcPeering = big.NewInt(1 << 0)
)

type VpcPeeringsPatchResponse struct {
	VpcPeering *VpcPeering `json:"vpc_peering,omitempty" url:"vpc_peering,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VpcPeeringsPatchResponse) GetVpcPeering() *VpcPeering {
	if v == nil {
		return nil
	}
	return v.VpcPeering
}

func (v *VpcPeeringsPatchResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VpcPeeringsPatchResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetVpcPeering sets the VpcPeering field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsPatchResponse) SetVpcPeering(vpcPeering *VpcPeering) {
	v.VpcPeering = vpcPeering
	v.require(vpcPeeringsPatchResponseFieldVpcPeering)
}

func (v *VpcPeeringsPatchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler VpcPeeringsPatchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VpcPeeringsPatchResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VpcPeeringsPatchResponse) MarshalJSON() ([]byte, error) {
	type embed VpcPeeringsPatchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VpcPeeringsPatchResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type VpcPeeringsCreateRequest struct {
	// The name of the VPC peering. Must be unique within the team and may only contain alphanumeric characters and dashes.
	Name *string `json:"name,omitempty" url:"-"`
	// An array of the two peered VPCs IDs.
	VpcIDs []string `json:"vpc_ids,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VpcPeeringsCreateRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

var (
	vpcPeeringsDeleteRequestFieldVpcPeeringID = big.NewInt(1 << 0)
)

type VpcPeeringsDeleteRequest struct {
	// A unique identifier for a VPC peering.
	VpcPeeringID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VpcPeeringsDeleteRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetVpcPeeringID sets the VpcPeeringID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsDeleteRequest) SetVpcPeeringID(vpcPeeringID string) {
	v.VpcPeeringID = vpcPeeringID
	v.require(vpcPeeringsDeleteRequestFieldVpcPeeringID)
}

var (
	vpcPeeringsGetRequestFieldVpcPeeringID = big.NewInt(1 << 0)
)

type VpcPeeringsGetRequest struct {
	// A unique identifier for a VPC peering.
	VpcPeeringID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VpcPeeringsGetRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetVpcPeeringID sets the VpcPeeringID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsGetRequest) SetVpcPeeringID(vpcPeeringID string) {
	v.VpcPeeringID = vpcPeeringID
	v.require(vpcPeeringsGetRequestFieldVpcPeeringID)
}

var (
	vpcPeeringsListRequestFieldPerPage = big.NewInt(1 << 0)
	vpcPeeringsListRequestFieldPage    = big.NewInt(1 << 1)
	vpcPeeringsListRequestFieldRegion  = big.NewInt(1 << 2)
)

type VpcPeeringsListRequest struct {
	// Number of items returned per page
	PerPage *int `json:"-" url:"per_page,omitempty"`
	// Which 'page' of paginated results to return.
	Page *int `json:"-" url:"page,omitempty"`
	// The slug identifier for the region where the resource is available.
	Region *RegionSlug `json:"-" url:"region,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VpcPeeringsListRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsListRequest) SetPerPage(perPage *int) {
	v.PerPage = perPage
	v.require(vpcPeeringsListRequestFieldPerPage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsListRequest) SetPage(page *int) {
	v.Page = page
	v.require(vpcPeeringsListRequestFieldPage)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsListRequest) SetRegion(region *RegionSlug) {
	v.Region = region
	v.require(vpcPeeringsListRequestFieldRegion)
}

var (
	vpcPeeringsPatchRequestFieldVpcPeeringID = big.NewInt(1 << 0)
)

type VpcPeeringsPatchRequest struct {
	// A unique identifier for a VPC peering.
	VpcPeeringID string               `json:"-" url:"-"`
	Body         *VpcPeeringUpdatable `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VpcPeeringsPatchRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetVpcPeeringID sets the VpcPeeringID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VpcPeeringsPatchRequest) SetVpcPeeringID(vpcPeeringID string) {
	v.VpcPeeringID = vpcPeeringID
	v.require(vpcPeeringsPatchRequestFieldVpcPeeringID)
}

func (v *VpcPeeringsPatchRequest) UnmarshalJSON(data []byte) error {
	body := new(VpcPeeringUpdatable)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	v.Body = body
	return nil
}

func (v *VpcPeeringsPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Body)
}
