// Code generated by Fern. DO NOT EDIT.

package functions_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	godonext "github.com/harshmaru7/godo-next"
	client "github.com/harshmaru7/godo-next/client"
	option "github.com/harshmaru7/godo-next/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestFunctionsListNamespacesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Functions.ListNamespaces(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsListNamespacesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsListNamespacesWithWireMock", "GET", "/v2/functions/namespaces", nil, 1)
}

func TestFunctionsCreateNamespaceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.CreateNamespace{
		Region: "nyc1",
		Label:  "my namespace",
	}
	_, invocationErr := client.Functions.CreateNamespace(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsCreateNamespaceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsCreateNamespaceWithWireMock", "POST", "/v2/functions/namespaces", nil, 1)
}

func TestFunctionsGetNamespaceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.FunctionsGetNamespaceRequest{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
	}
	_, invocationErr := client.Functions.GetNamespace(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsGetNamespaceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsGetNamespaceWithWireMock", "GET", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", nil, 1)
}

func TestFunctionsDeleteNamespaceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.FunctionsDeleteNamespaceRequest{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
	}
	invocationErr := client.Functions.DeleteNamespace(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsDeleteNamespaceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsDeleteNamespaceWithWireMock", "DELETE", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", nil, 1)
}

func TestFunctionsListTriggersWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.FunctionsListTriggersRequest{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
	}
	_, invocationErr := client.Functions.ListTriggers(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsListTriggersWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsListTriggersWithWireMock", "GET", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/triggers", nil, 1)
}

func TestFunctionsCreateTriggerWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.CreateTrigger{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
		Name:        "my trigger",
		Function:    "hello",
		Type:        "SCHEDULED",
		IsEnabled:   true,
		ScheduledDetails: &godonext.ScheduledDetails{
			Cron: "* * * * *",
		},
	}
	_, invocationErr := client.Functions.CreateTrigger(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsCreateTriggerWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsCreateTriggerWithWireMock", "POST", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/triggers", nil, 1)
}

func TestFunctionsGetTriggerWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.FunctionsGetTriggerRequest{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
		TriggerName: "my trigger",
	}
	_, invocationErr := client.Functions.GetTrigger(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsGetTriggerWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsGetTriggerWithWireMock", "GET", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/triggers/my trigger", nil, 1)
}

func TestFunctionsUpdateTriggerWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.UpdateTrigger{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
		TriggerName: "my trigger",
	}
	_, invocationErr := client.Functions.UpdateTrigger(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsUpdateTriggerWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsUpdateTriggerWithWireMock", "PUT", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/triggers/my trigger", nil, 1)
}

func TestFunctionsDeleteTriggerWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.FunctionsDeleteTriggerRequest{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
		TriggerName: "my trigger",
	}
	invocationErr := client.Functions.DeleteTrigger(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsDeleteTriggerWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsDeleteTriggerWithWireMock", "DELETE", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/triggers/my trigger", nil, 1)
}

func TestFunctionsFunctionsAccessKeyListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.FunctionsAccessKeyListRequest{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
	}
	_, invocationErr := client.Functions.FunctionsAccessKeyList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsFunctionsAccessKeyListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsFunctionsAccessKeyListWithWireMock", "GET", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/keys", nil, 1)
}

func TestFunctionsFunctionsAccessKeyCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.AccessKeyCreateRequest{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
		Name:        "my-function-access-key",
	}
	_, invocationErr := client.Functions.FunctionsAccessKeyCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsFunctionsAccessKeyCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsFunctionsAccessKeyCreateWithWireMock", "POST", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/keys", nil, 1)
}

func TestFunctionsFunctionsAccessKeyUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.FunctionsAccessKeyUpdateRequest{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
		KeyID:       "dof-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
		Name:        "updated-key-name",
	}
	_, invocationErr := client.Functions.FunctionsAccessKeyUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsFunctionsAccessKeyUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsFunctionsAccessKeyUpdateWithWireMock", "PUT", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/keys/dof-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", nil, 1)
}

func TestFunctionsFunctionsAccessKeyDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.FunctionsAccessKeyDeleteRequest{
		NamespaceID: "fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
		KeyID:       "dof-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
	}
	_, invocationErr := client.Functions.FunctionsAccessKeyDelete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFunctionsFunctionsAccessKeyDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFunctionsFunctionsAccessKeyDeleteWithWireMock", "DELETE", "/v2/functions/namespaces/fn-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/keys/dof-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", nil, 1)
}
