// Code generated by Fern. DO NOT EDIT.

package agentinference

import (
	context "context"

	godonext "github.com/harshmaru7/godo-next"
	core "github.com/harshmaru7/godo-next/core"
	internal "github.com/harshmaru7/godo-next/internal"
	option "github.com/harshmaru7/godo-next/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Creates a model response for the given chat conversation via a customer-provisioned
// agent endpoint.
func (c *Client) AgentInferenceCreateChatCompletion(
	ctx context.Context,
	request *godonext.AgentInferenceCreateChatCompletionRequest,
	opts ...option.RequestOption,
) (*godonext.ChatCompletionResponse, error) {
	response, err := c.WithRawResponse.AgentInferenceCreateChatCompletion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
