// Code generated by Fern. DO NOT EDIT.

package spaceskeys

import (
	context "context"
	http "net/http"

	godonext "github.com/harshmaru7/godo-next"
	core "github.com/harshmaru7/godo-next/core"
	internal "github.com/harshmaru7/godo-next/internal"
	option "github.com/harshmaru7/godo-next/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) SpacesKeyList(
	ctx context.Context,
	request *godonext.SpacesKeyListRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SpacesKeyListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := baseURL + "/v2/spaces/keys"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *godonext.SpacesKeyListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SpacesKeyListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SpacesKeyCreate(
	ctx context.Context,
	request *godonext.Key,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SpacesKeyCreateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := baseURL + "/v2/spaces/keys"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *godonext.SpacesKeyCreateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SpacesKeyCreateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SpacesKeyGet(
	ctx context.Context,
	request *godonext.SpacesKeyGetRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SpacesKeyGetResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/spaces/keys/%v",
		request.AccessKey,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *godonext.SpacesKeyGetResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SpacesKeyGetResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SpacesKeyUpdate(
	ctx context.Context,
	request *godonext.SpacesKeyUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SpacesKeyUpdateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/spaces/keys/%v",
		request.AccessKey,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *godonext.SpacesKeyUpdateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SpacesKeyUpdateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) SpacesKeyDelete(
	ctx context.Context,
	request *godonext.SpacesKeyDeleteRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/spaces/keys/%v",
		request.AccessKey,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) SpacesKeyPatch(
	ctx context.Context,
	request *godonext.SpacesKeyPatchRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SpacesKeyPatchResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/spaces/keys/%v",
		request.AccessKey,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *godonext.SpacesKeyPatchResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SpacesKeyPatchResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
