// Code generated by Fern. DO NOT EDIT.

// DigitalOcean offers the ability for you to create a
// [private container registry](https://docs.digitalocean.com/products/container-registry/)
// to store your Docker images for use with your Kubernetes clusters. This
// container registry runs inside the same datacenters as your cluster,
// ensuring reliable and performant rollout of image deployments.
//
// You can only create one registry per DigitalOcean account, but you can use
// that registry to create as many repositories as you wish.
package containerregistry
