// Code generated by Fern. DO NOT EDIT.

package serverlessinference

import (
	context "context"

	godonext "github.com/harshmaru7/godo-next"
	core "github.com/harshmaru7/godo-next/core"
	internal "github.com/harshmaru7/godo-next/internal"
	option "github.com/harshmaru7/godo-next/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Creates a model response for the given chat conversation.
func (c *Client) InferenceCreateChatCompletion(
	ctx context.Context,
	request *godonext.ChatCompletionRequest,
	opts ...option.RequestOption,
) (*godonext.ChatCompletionResponse, error) {
	response, err := c.WithRawResponse.InferenceCreateChatCompletion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Send a structured list of input messages with text and/or image content, and the model will generate the next message in the conversation.
func (c *Client) InferenceCreateMessages(
	ctx context.Context,
	request *godonext.MessagesCreateRequest,
	opts ...option.RequestOption,
) (*godonext.MessagesCreateResponse, error) {
	response, err := c.WithRawResponse.InferenceCreateMessages(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create vector embeddings for one or more text inputs. OpenAI-compatible request and response. Unknown fields in the request body are rejected. There is no streaming response for this endpoint.
func (c *Client) InferenceCreateEmbedding(
	ctx context.Context,
	request *godonext.EmbeddingsRequest,
	opts ...option.RequestOption,
) (*godonext.EmbeddingsResponse, error) {
	response, err := c.WithRawResponse.InferenceCreateEmbedding(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a high-quality image from a text prompt using GPT-IMAGE-1, the latest image generation model with automatic prompt optimization and enhanced visual capabilities.
func (c *Client) InferenceCreateImage(
	ctx context.Context,
	request *godonext.CreateImageRequest,
	opts ...option.RequestOption,
) (*godonext.ImagesResponse, error) {
	response, err := c.WithRawResponse.InferenceCreateImage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Lists the currently available models, and provides basic information about each one such as the owner and availability.
func (c *Client) InferenceListModels(
	ctx context.Context,
	opts ...option.RequestOption,
) (*godonext.ListModelsResponse, error) {
	response, err := c.WithRawResponse.InferenceListModels(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Generate text responses from text prompts. This endpoint supports both streaming and non-streaming responses for supported text models.
func (c *Client) InferenceCreateResponse(
	ctx context.Context,
	request *godonext.CreateResponseRequest,
	opts ...option.RequestOption,
) (*godonext.CreateResponseResponse, error) {
	response, err := c.WithRawResponse.InferenceCreateResponse(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Generate Image, Audio, or Text-to-Speech Using fal Models. This endpoint starts an asynchronous job and returns a request_id. The job status is QUEUED initially. Use the request_id to poll for the result.
func (c *Client) InferenceCreateAsyncInvoke(
	ctx context.Context,
	request *godonext.AsyncInvokeRequest,
	opts ...option.RequestOption,
) (*godonext.AsyncInvokeResponse, error) {
	response, err := c.WithRawResponse.InferenceCreateAsyncInvoke(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
