// Code generated by Fern. DO NOT EDIT.

// DigitalOcean Gradient™ AI Agentic Cloud allows access to serverless inference models.
// You can access models by providing an inference key.
//
// **Note:** The Serverless Inference API uses a separate base URL (`https://inference.do-ai.run`)
// and is independent of the main DigitalOcean control-plane API (`https://api.digitalocean.com`).
package serverlessinference
