// Code generated by Fern. DO NOT EDIT.

package security

import (
	context "context"
	http "net/http"

	godonext "github.com/harshmaru7/godo-next"
	core "github.com/harshmaru7/godo-next/core"
	internal "github.com/harshmaru7/godo-next/internal"
	option "github.com/harshmaru7/godo-next/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListScans(
	ctx context.Context,
	request *godonext.SecurityListScansRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SecurityListScansResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := baseURL + "/v2/security/scans"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *godonext.SecurityListScansResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SecurityListScansResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateScan(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SecurityCreateScanResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := baseURL + "/v2/security/scans"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *godonext.SecurityCreateScanResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SecurityCreateScanResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetScan(
	ctx context.Context,
	request *godonext.SecurityGetScanRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SecurityGetScanResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/security/scans/%v",
		request.ScanID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *godonext.SecurityGetScanResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SecurityGetScanResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetLatestScan(
	ctx context.Context,
	request *godonext.SecurityGetLatestScanRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SecurityGetLatestScanResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := baseURL + "/v2/security/scans/latest"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *godonext.SecurityGetLatestScanResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SecurityGetLatestScanResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateScanRule(
	ctx context.Context,
	request *godonext.SecurityCreateScanRuleRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := baseURL + "/v2/security/scans/rules"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}

func (r *RawClient) ListScanFindingAffectedResources(
	ctx context.Context,
	request *godonext.SecurityListScanFindingAffectedResourcesRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SecurityListScanFindingAffectedResourcesResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/security/scans/%v/findings/%v/affected_resources",
		request.ScanID,
		request.FindingUUID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *godonext.SecurityListScanFindingAffectedResourcesResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SecurityListScanFindingAffectedResourcesResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListSettings(
	ctx context.Context,
	request *godonext.SecurityListSettingsRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.Settings], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := baseURL + "/v2/security/settings"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *godonext.Settings
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.Settings]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateSettingsPlan(
	ctx context.Context,
	request *godonext.SecurityUpdateSettingsPlanRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SecurityUpdateSettingsPlanResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := baseURL + "/v2/security/settings/plan"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *godonext.SecurityUpdateSettingsPlanResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SecurityUpdateSettingsPlanResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateSuppression(
	ctx context.Context,
	request *godonext.SecurityCreateSuppressionRequest,
	opts ...option.RequestOption,
) (*core.Response[*godonext.SuppressedResourceRoot], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := baseURL + "/v2/security/settings/suppressions"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *godonext.SuppressedResourceRoot
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*godonext.SuppressedResourceRoot]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteSuppression(
	ctx context.Context,
	request *godonext.SecurityDeleteSuppressionRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		internal.ResolveEnvironmentBaseURL(
			options.Environment,
			"Base",
		),
		r.baseURL,
		internal.ResolveEnvironmentBaseURL(
			r.options.Environment,
			"Base",
		),
		"https://api.digitalocean.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/security/settings/suppressions/%v",
		request.SuppressionUUID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(godonext.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}
