// Code generated by Fern. DO NOT EDIT.

// In order to perform SSL termination on load balancers, DigitalOcean offers
// two types of [SSL certificate management](https://docs.digitalocean.com/platform/teams/manage-certificates):
//
// * **Custom**: User-generated certificates may be uploaded to DigitalOcean
// where they will be placed in a fully encrypted and isolated storage system.
//
// * **Let's Encrypt**: Certificates may be automatically generated by
// DigitalOcean utilizing an integration with Let's Encrypt, the free and
// open certificate authority. These certificates will also be automatically
// renewed as required.
package certificates
