// Code generated by Fern. DO NOT EDIT.

// Batch Inference is an asynchronous processing capability designed to help
// you scale high-volume AI projects more efficiently. Ideal for heavy-duty
// workloads like large-scale data classification, evaluations, and content
// enrichment, you can submit thousands or even millions of requests in a
// single job with a guaranteed results window of 24 hours. By utilizing
// off-peak GPU capacity, Batch Inference provides high-performance LLM
// access at a significantly reduced price point compared to standard
// synchronous APIs, making it a cost-effective choice for non-interactive
// workloads.
package batchinference
