// Code generated by Fern. DO NOT EDIT.

package droplet_autoscale_pools_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	godonext "github.com/harshmaru7/godo-next"
	client "github.com/harshmaru7/godo-next/client"
	option "github.com/harshmaru7/godo-next/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestDropletAutoscalePoolsAutoscalepoolsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.AutoscalepoolsListRequest{
		Name: godonext.String(
			"my-autoscale-pool",
		),
	}
	_, invocationErr := client.DropletAutoscalePools.AutoscalepoolsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDropletAutoscalePoolsAutoscalepoolsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDropletAutoscalePoolsAutoscalepoolsListWithWireMock", "GET", "/v2/droplets/autoscale", map[string]interface{}{"name": "my-autoscale-pool"}, 1)
}

func TestDropletAutoscalePoolsAutoscalepoolsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.AutoscalePoolCreate{
		Name: "my-autoscale-pool",
		Config: &godonext.AutoscalePoolCreateConfig{
			AutoscalePoolDynamicConfig: &godonext.AutoscalePoolDynamicConfig{
				MinInstances: 1,
				MaxInstances: 5,
				TargetCPUUtilization: godonext.Float64(
					0.5,
				),
				CooldownMinutes: godonext.Int(
					10,
				),
			},
		},
		DropletTemplate: &godonext.AutoscalePoolDropletTemplate{
			Name: godonext.String(
				"example.com",
			),
			Region: godonext.AutoscalePoolDropletTemplateRegionNyc3,
			Size:   "c-2",
			Image:  "ubuntu-20-04-x64",
			SSHKeys: []string{
				"3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45",
			},
			Tags: []string{
				"env:prod",
				"web",
			},
			VpcUUID: godonext.String(
				"760e09ef-dc84-11e8-981e-3cfdfeaae000",
			),
			Ipv6: godonext.Bool(
				true,
			),
			UserData: godonext.String(
				`#cloud-config
                    runcmd:
                      - touch /test.txt
                    `,
			),
		},
	}
	_, invocationErr := client.DropletAutoscalePools.AutoscalepoolsCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDropletAutoscalePoolsAutoscalepoolsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDropletAutoscalePoolsAutoscalepoolsCreateWithWireMock", "POST", "/v2/droplets/autoscale", nil, 1)
}

func TestDropletAutoscalePoolsAutoscalepoolsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.AutoscalepoolsGetRequest{
		AutoscalePoolID: "0d3db13e-a604-4944-9827-7ec2642d32ac",
	}
	_, invocationErr := client.DropletAutoscalePools.AutoscalepoolsGet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDropletAutoscalePoolsAutoscalepoolsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDropletAutoscalePoolsAutoscalepoolsGetWithWireMock", "GET", "/v2/droplets/autoscale/0d3db13e-a604-4944-9827-7ec2642d32ac", nil, 1)
}

func TestDropletAutoscalePoolsAutoscalepoolsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.AutoscalepoolsUpdateRequest{
		AutoscalePoolID: "0d3db13e-a604-4944-9827-7ec2642d32ac",
		Body: &godonext.AutoscalePoolCreate{
			Name: "my-autoscale-pool",
			Config: &godonext.AutoscalePoolCreateConfig{
				AutoscalePoolStaticConfig: &godonext.AutoscalePoolStaticConfig{
					TargetNumberInstances: 2,
				},
			},
			DropletTemplate: &godonext.AutoscalePoolDropletTemplate{
				Name: godonext.String(
					"example.com",
				),
				Region: godonext.AutoscalePoolDropletTemplateRegionNyc3,
				Size:   "c-2",
				Image:  "ubuntu-20-04-x64",
				SSHKeys: []string{
					"3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45",
				},
				Tags: []string{
					"env:prod",
					"web",
				},
				VpcUUID: godonext.String(
					"760e09ef-dc84-11e8-981e-3cfdfeaae000",
				),
				Ipv6: godonext.Bool(
					true,
				),
				UserData: godonext.String(
					`#cloud-config
                        runcmd:
                          - touch /test.txt
                        `,
				),
			},
		},
	}
	_, invocationErr := client.DropletAutoscalePools.AutoscalepoolsUpdate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDropletAutoscalePoolsAutoscalepoolsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDropletAutoscalePoolsAutoscalepoolsUpdateWithWireMock", "PUT", "/v2/droplets/autoscale/0d3db13e-a604-4944-9827-7ec2642d32ac", nil, 1)
}

func TestDropletAutoscalePoolsAutoscalepoolsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.AutoscalepoolsDeleteRequest{
		AutoscalePoolID: "0d3db13e-a604-4944-9827-7ec2642d32ac",
	}
	invocationErr := client.DropletAutoscalePools.AutoscalepoolsDelete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDropletAutoscalePoolsAutoscalepoolsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDropletAutoscalePoolsAutoscalepoolsDeleteWithWireMock", "DELETE", "/v2/droplets/autoscale/0d3db13e-a604-4944-9827-7ec2642d32ac", nil, 1)
}

func TestDropletAutoscalePoolsAutoscalepoolsDeleteDangerousWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.AutoscalepoolsDeleteDangerousRequest{
		AutoscalePoolID: "0d3db13e-a604-4944-9827-7ec2642d32ac",
		Dangerous:       true,
	}
	invocationErr := client.DropletAutoscalePools.AutoscalepoolsDeleteDangerous(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDropletAutoscalePoolsAutoscalepoolsDeleteDangerousWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDropletAutoscalePoolsAutoscalepoolsDeleteDangerousWithWireMock", "DELETE", "/v2/droplets/autoscale/0d3db13e-a604-4944-9827-7ec2642d32ac/dangerous", nil, 1)
}

func TestDropletAutoscalePoolsAutoscalepoolsListMembersWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.AutoscalepoolsListMembersRequest{
		AutoscalePoolID: "0d3db13e-a604-4944-9827-7ec2642d32ac",
	}
	_, invocationErr := client.DropletAutoscalePools.AutoscalepoolsListMembers(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDropletAutoscalePoolsAutoscalepoolsListMembersWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDropletAutoscalePoolsAutoscalepoolsListMembersWithWireMock", "GET", "/v2/droplets/autoscale/0d3db13e-a604-4944-9827-7ec2642d32ac/members", nil, 1)
}

func TestDropletAutoscalePoolsAutoscalepoolsListHistoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.AutoscalepoolsListHistoryRequest{
		AutoscalePoolID: "0d3db13e-a604-4944-9827-7ec2642d32ac",
	}
	_, invocationErr := client.DropletAutoscalePools.AutoscalepoolsListHistory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDropletAutoscalePoolsAutoscalepoolsListHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDropletAutoscalePoolsAutoscalepoolsListHistoryWithWireMock", "GET", "/v2/droplets/autoscale/0d3db13e-a604-4944-9827-7ec2642d32ac/history", nil, 1)
}
