// Code generated by Fern. DO NOT EDIT.

// DigitalOcean Reserved IPv6s are publicly-accessible static IP addresses that can be
// mapped to one of your Droplets. They can be used to create highly available
// setups or other configurations requiring movable addresses.
//
// Reserved IPv6s are bound to a specific region.
package reservedipv6
