// Code generated by Fern. DO NOT EDIT.

package partner_network_connect_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	godonext "github.com/harshmaru7/godo-next"
	client "github.com/harshmaru7/godo-next/client"
	option "github.com/harshmaru7/godo-next/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPartnerNetworkConnectPartnerAttachmentsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.PartnerAttachmentsListRequest{}
	_, invocationErr := client.PartnerNetworkConnect.PartnerAttachmentsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPartnerNetworkConnectPartnerAttachmentsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPartnerNetworkConnectPartnerAttachmentsListWithWireMock", "GET", "/v2/partner_network_connect/attachments", nil, 1)
}

func TestPartnerNetworkConnectPartnerAttachmentsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.PartnerAttachmentWritable{
		Name:                      "env.prod-partner-network-connect",
		ConnectionBandwidthInMbps: 1000,
		Region:                    godonext.PartnerAttachmentWritableRegionNyc,
		NaasProvider:              "megaport",
		VpcIDs: []string{
			"c140286f-e6ce-4131-8b7b-df4590ce8d6a",
			"994a2735-dc84-11e8-80bc-3cfdfea9fba1",
		},
	}
	_, invocationErr := client.PartnerNetworkConnect.PartnerAttachmentsCreate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPartnerNetworkConnectPartnerAttachmentsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPartnerNetworkConnectPartnerAttachmentsCreateWithWireMock", "POST", "/v2/partner_network_connect/attachments", nil, 1)
}

func TestPartnerNetworkConnectPartnerAttachmentsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.PartnerAttachmentsGetRequest{
		PaID: "4de7ac8b-495b-4884-9a69-1050c6793cd6",
	}
	_, invocationErr := client.PartnerNetworkConnect.PartnerAttachmentsGet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPartnerNetworkConnectPartnerAttachmentsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPartnerNetworkConnectPartnerAttachmentsGetWithWireMock", "GET", "/v2/partner_network_connect/attachments/4de7ac8b-495b-4884-9a69-1050c6793cd6", nil, 1)
}

func TestPartnerNetworkConnectPartnerAttachmentsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.PartnerAttachmentsDeleteRequest{
		PaID: "4de7ac8b-495b-4884-9a69-1050c6793cd6",
	}
	_, invocationErr := client.PartnerNetworkConnect.PartnerAttachmentsDelete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPartnerNetworkConnectPartnerAttachmentsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPartnerNetworkConnectPartnerAttachmentsDeleteWithWireMock", "DELETE", "/v2/partner_network_connect/attachments/4de7ac8b-495b-4884-9a69-1050c6793cd6", nil, 1)
}

func TestPartnerNetworkConnectPartnerAttachmentsPatchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.PartnerAttachmentsPatchRequest{
		PaID: "4de7ac8b-495b-4884-9a69-1050c6793cd6",
		Body: &godonext.PartnerAttachmentUpdatable{
			PartnerAttachmentUpdatableName: &godonext.PartnerAttachmentUpdatableName{
				Name: "env.prod-partner-network-connect",
			},
		},
	}
	_, invocationErr := client.PartnerNetworkConnect.PartnerAttachmentsPatch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPartnerNetworkConnectPartnerAttachmentsPatchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPartnerNetworkConnectPartnerAttachmentsPatchWithWireMock", "PATCH", "/v2/partner_network_connect/attachments/4de7ac8b-495b-4884-9a69-1050c6793cd6", nil, 1)
}

func TestPartnerNetworkConnectPartnerAttachmentsGetBgpAuthKeyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.PartnerAttachmentsGetBgpAuthKeyRequest{
		PaID: "4de7ac8b-495b-4884-9a69-1050c6793cd6",
	}
	_, invocationErr := client.PartnerNetworkConnect.PartnerAttachmentsGetBgpAuthKey(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPartnerNetworkConnectPartnerAttachmentsGetBgpAuthKeyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPartnerNetworkConnectPartnerAttachmentsGetBgpAuthKeyWithWireMock", "GET", "/v2/partner_network_connect/attachments/4de7ac8b-495b-4884-9a69-1050c6793cd6/bgp_auth_key", nil, 1)
}

func TestPartnerNetworkConnectPartnerAttachmentsListRemoteRoutesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.PartnerAttachmentsListRemoteRoutesRequest{
		PaID: "4de7ac8b-495b-4884-9a69-1050c6793cd6",
	}
	_, invocationErr := client.PartnerNetworkConnect.PartnerAttachmentsListRemoteRoutes(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPartnerNetworkConnectPartnerAttachmentsListRemoteRoutesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPartnerNetworkConnectPartnerAttachmentsListRemoteRoutesWithWireMock", "GET", "/v2/partner_network_connect/attachments/4de7ac8b-495b-4884-9a69-1050c6793cd6/remote_routes", nil, 1)
}

func TestPartnerNetworkConnectPartnerAttachmentsGetServiceKeyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.PartnerAttachmentsGetServiceKeyRequest{
		PaID: "4de7ac8b-495b-4884-9a69-1050c6793cd6",
	}
	_, invocationErr := client.PartnerNetworkConnect.PartnerAttachmentsGetServiceKey(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPartnerNetworkConnectPartnerAttachmentsGetServiceKeyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPartnerNetworkConnectPartnerAttachmentsGetServiceKeyWithWireMock", "GET", "/v2/partner_network_connect/attachments/4de7ac8b-495b-4884-9a69-1050c6793cd6/service_key", nil, 1)
}

func TestPartnerNetworkConnectPartnerAttachmentsCreateServiceKeyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.PartnerAttachmentsCreateServiceKeyRequest{
		PaID: "4de7ac8b-495b-4884-9a69-1050c6793cd6",
	}
	_, invocationErr := client.PartnerNetworkConnect.PartnerAttachmentsCreateServiceKey(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPartnerNetworkConnectPartnerAttachmentsCreateServiceKeyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPartnerNetworkConnectPartnerAttachmentsCreateServiceKeyWithWireMock", "POST", "/v2/partner_network_connect/attachments/4de7ac8b-495b-4884-9a69-1050c6793cd6/service_key", nil, 1)
}
