// Code generated by Fern. DO NOT EDIT.

package serverless_inference_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	godonext "github.com/harshmaru7/godo-next"
	client "github.com/harshmaru7/godo-next/client"
	option "github.com/harshmaru7/godo-next/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestServerlessInferenceInferenceCreateChatCompletionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.ChatCompletionRequest{
		Messages: []*godonext.ChatMessage{
			&godonext.ChatMessage{
				Role: godonext.ChatMessageRoleSystem,
			},
		},
		Model: "llama3-8b-instruct",
	}
	_, invocationErr := client.ServerlessInference.InferenceCreateChatCompletion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestServerlessInferenceInferenceCreateChatCompletionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestServerlessInferenceInferenceCreateChatCompletionWithWireMock", "POST", "/v1/chat/completions", nil, 1)
}

func TestServerlessInferenceInferenceCreateMessagesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.MessagesCreateRequest{
		Model:     "claude-opus-4-6",
		MaxTokens: 1,
		Messages: []*godonext.MessagesAPIMessageParam{
			&godonext.MessagesAPIMessageParam{
				Role: godonext.MessagesAPIMessageParamRoleUser,
				Content: &godonext.MessagesAPIMessageParamContent{
					String: "content",
				},
			},
		},
	}
	_, invocationErr := client.ServerlessInference.InferenceCreateMessages(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestServerlessInferenceInferenceCreateMessagesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestServerlessInferenceInferenceCreateMessagesWithWireMock", "POST", "/v1/messages", nil, 1)
}

func TestServerlessInferenceInferenceCreateEmbeddingWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.EmbeddingsRequest{
		Model: "qwen3-embedding-0.6b",
		Input: &godonext.EmbeddingsRequestInput{
			String: "hello world",
		},
	}
	_, invocationErr := client.ServerlessInference.InferenceCreateEmbedding(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestServerlessInferenceInferenceCreateEmbeddingWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestServerlessInferenceInferenceCreateEmbeddingWithWireMock", "POST", "/v1/embeddings", nil, 1)
}

func TestServerlessInferenceInferenceCreateImageWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.CreateImageRequest{
		Prompt: "A cute baby sea otter floating on its back in calm blue water",
		Model:  "openai-gpt-image-1",
		N:      1,
	}
	_, invocationErr := client.ServerlessInference.InferenceCreateImage(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestServerlessInferenceInferenceCreateImageWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestServerlessInferenceInferenceCreateImageWithWireMock", "POST", "/v1/images/generations", nil, 1)
}

func TestServerlessInferenceInferenceListModelsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.ServerlessInference.InferenceListModels(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestServerlessInferenceInferenceListModelsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestServerlessInferenceInferenceListModelsWithWireMock", "GET", "/v1/models", nil, 1)
}

func TestServerlessInferenceInferenceCreateResponseWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.CreateResponseRequest{
		Model: "openai-gpt-oss-20b",
		Input: &godonext.CreateResponseRequestInput{
			String: "What is the capital of France?",
		},
	}
	_, invocationErr := client.ServerlessInference.InferenceCreateResponse(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestServerlessInferenceInferenceCreateResponseWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestServerlessInferenceInferenceCreateResponseWithWireMock", "POST", "/v1/responses", nil, 1)
}

func TestServerlessInferenceInferenceCreateAsyncInvokeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.AsyncInvokeRequest{
		ModelID: "fal-ai/flux/schnell",
		Input: &godonext.AsyncInvokeRequestInput{
			Prompt: godonext.String(
				"A futuristic city at sunset",
			),
		},
	}
	_, invocationErr := client.ServerlessInference.InferenceCreateAsyncInvoke(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestServerlessInferenceInferenceCreateAsyncInvokeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestServerlessInferenceInferenceCreateAsyncInvokeWithWireMock", "POST", "/v1/async-invoke", nil, 1)
}
