// Code generated by Fern. DO NOT EDIT.

package tags_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	godonext "github.com/harshmaru7/godo-next"
	client "github.com/harshmaru7/godo-next/client"
	option "github.com/harshmaru7/godo-next/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestTagsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.TagsListRequest{}
	_, invocationErr := client.Tags.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTagsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTagsListWithWireMock", "GET", "/v2/tags", nil, 1)
}

func TestTagsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.Tags{}
	_, invocationErr := client.Tags.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTagsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTagsCreateWithWireMock", "POST", "/v2/tags", nil, 1)
}

func TestTagsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.TagsGetRequest{
		TagID: "awesome",
	}
	_, invocationErr := client.Tags.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTagsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTagsGetWithWireMock", "GET", "/v2/tags/awesome", nil, 1)
}

func TestTagsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.TagsDeleteRequest{
		TagID: "awesome",
	}
	invocationErr := client.Tags.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTagsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTagsDeleteWithWireMock", "DELETE", "/v2/tags/awesome", nil, 1)
}

func TestTagsAssignResourcesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.TagsAssignResourcesRequest{
		TagID: "awesome",
		Body: &godonext.TagsResource{
			Resources: []*godonext.TagsResourceResourcesItem{
				&godonext.TagsResourceResourcesItem{
					ResourceID: godonext.String(
						"9569411",
					),
					ResourceType: godonext.TagsResourceResourcesItemResourceTypeDroplet.Ptr(),
				},
				&godonext.TagsResourceResourcesItem{
					ResourceID: godonext.String(
						"7555620",
					),
					ResourceType: godonext.TagsResourceResourcesItemResourceTypeImage.Ptr(),
				},
				&godonext.TagsResourceResourcesItem{
					ResourceID: godonext.String(
						"3d80cb72-342b-4aaa-b92e-4e4abb24a933",
					),
					ResourceType: godonext.TagsResourceResourcesItemResourceTypeVolume.Ptr(),
				},
			},
		},
	}
	invocationErr := client.Tags.AssignResources(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTagsAssignResourcesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTagsAssignResourcesWithWireMock", "POST", "/v2/tags/awesome/resources", nil, 1)
}

func TestTagsUnassignResourcesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &godonext.TagsUnassignResourcesRequest{
		TagID: "awesome",
		Body: &godonext.TagsResource{
			Resources: []*godonext.TagsResourceResourcesItem{
				&godonext.TagsResourceResourcesItem{
					ResourceID: godonext.String(
						"9569411",
					),
					ResourceType: godonext.TagsResourceResourcesItemResourceTypeDroplet.Ptr(),
				},
				&godonext.TagsResourceResourcesItem{
					ResourceID: godonext.String(
						"7555620",
					),
					ResourceType: godonext.TagsResourceResourcesItemResourceTypeImage.Ptr(),
				},
				&godonext.TagsResourceResourcesItem{
					ResourceID: godonext.String(
						"3d80cb72-342b-4aaa-b92e-4e4abb24a933",
					),
					ResourceType: godonext.TagsResourceResourcesItemResourceTypeVolume.Ptr(),
				},
			},
		},
	}
	invocationErr := client.Tags.UnassignResources(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTagsUnassignResourcesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTagsUnassignResourcesWithWireMock", "DELETE", "/v2/tags/awesome/resources", nil, 1)
}
